### ISSUE TITLE
Customizable Text display command.

### ISSUE THREAD

**Issue by Xyvius** [SimpleServer/SimpleServer#100]
I have an idea for a possible command which could be used in a variety of ways to help improve the personalization of a server.

A "/read" or "/show" command which would allow the users to specify a text doc to display.

Example:

/read testdoc

Would display the text file "testdoc.txt" supporting color codes, etc.

I can't imagine that this would be too hard to implement as this feature already functions with the /motd and /rules commands.
This would simply be a small variant which would allow the user to specify a custom file for display.

Uses:

This would have a wide range of uses including the ability for Ops to set up documentation detailing things like rankings, "disciplinary" procedures (jailing, etc), FAQS, Membership info, and server technical data that the ops wanted the users to have access to.  Not to mention the fun aspects like setting up "treasure hunts", "quests" and lengthy area information that is way too long to fit on a sign.

Thanks for your consideration,

Joseph (Xyvius)

P.S.  I would suggest having some kind of "protection" from having the command used to display server config files, etc.

**Comment by dola** [comment]
this indeed sounds nice.
I would place every such _doc_ in a separate folder inside the _simpleserver/_ folder that already exists. (with all the config files)
And with caching of the files we could even guarantee some good performance :)
