### ISSUE TITLE
Renaming of commands

### ISSUE THREAD

**Issue by Xyvius** [SimpleServer/SimpleServer#101]
a _rename_ attribute for commands in _permissions.xml_ would allow users to avoid command name conflicts as well as adjust command names to be more intuitive based on the Ops intended use

Example:

`<command name="setgroup" rename="setrank" allow="4,5" />`

Would rename the command "/setgroup" to "/setrank" making the "/setgroup" command available for other mods, etc.

**Comment by acertain** [comment]
doesn't `alias=` do the same?

**Comment by heapoutofspace** [comment]
No, with rename the original name can be used for mods.
