### ISSUE TITLE
Reload via console under Bukkit

### ISSUE THREAD

**Issue by Triforce9** [SimpleServer/SimpleServer#102]
I recently moved over to running CraftBukkit and I've noticed that typing "reload" in the console will only reload SimpleServer, and not Bukkit. While typing /reload in game (with permissions.xml set forward="true" for that command) does reload both systems (of course).

**Comment by dola** [comment]
This commit should fix this problem. Server commands use now the same forwarding settings from _permissions.xml_ as player commands do. So options `forward="true"` and `forward="only"` will forward server commands.

**Comment by Triforce9** [comment]
This issue has re-reared it's ugly head it seems
