### ISSUE TITLE
Auto backup fails to run.

### ISSUE THREAD

**Issue by jessearmstrong** [SimpleServer/SimpleServer#104]
I didn't know for sure if this was a configuration issue or a bug, but I can't get auto backups to run through the wrapper. If I force a backup, everything works perfectly but I can't get the auto to work at all. I will append my config file in case I am just setting it up incorrectly. 

Also locked chests do not keep others from opening them on my server. The chests say locked but they can be opened and looted by the others. I am the owner (group 5) and those in group 3 (mods) can open and loot my chests. Didn't test with a lower group.

Thanks in advance for your help.

_
# Fri Jul 29 15:46:02 CDT 2011

allowFlight=true
allowNether=true
alternateJarFile=
announceBackup=true
announceRestart=true
announceSave=true
autoBackup=true
autoBackupMins=30
autoRestart=false
autoRestartMins=240
autoSave=false
autoSaveMins=5
c10tArgs=
c10tMins=60
chatConsoleToOps=false
custAuth=false
debug=false
defaultGroup=1
enableRcon=false
enableTelnet=false
exitOnFailure=true
forwardAllCommands=false
freezeTime=
internalPort=25568
ipAddress=0.0.0.0
javaArguments=
keepBackupHours=24
levelName=world
localChatRadius=30
maxPlayers=16
memory=1024
msgFormat=\u00A7%3$s<%1$s>\u00A7f 
msgTitleFormat=\u00A7%3$s<[%2$s]%1$s>\u00A7f 
msgWrap=true
onlineMode=true
overwriteArguments=false
port=25567
pvp=true
rconPassword=
rconPort=25500
serverLanguage=en
showListOnConnect=false
spawnAnimals=true
spawnMonsters=false
telnetPassword=
telnetPort=25505
useMsgFormats=true
useSlashes=true
useWhitelist=false
useXincgc=true
viewDistance=10
worldSeed=Junius St.

**Comment by dola** [comment]
The backup should work with this configuration. There was a bug that we already fixed, which lead to no backups being made if no player is online in the exact moment the timer invokes the backup method. But still if a player is online for more than 30 minutes (your backup interval) it should be done at least once...
I will have an other look over the backup things to determine if there's still some bug in it.

And the thing with chestlocks is normal with your configuration. If you have a look to your permissions.xml you will most likely find a line similar to this one:
`<group color="9" id="3" ignoreChestlocks="true" name="Mod" showTitle="false"/>`
in the `<groups>` section.

The attribute `ignoreChestlocks="true"` makes that every mod can open all chests. So either you trust your mods or you can set the attribute to `false` so they can only open their own chests.

**Comment by jessearmstrong** [comment]
As if by magic, the backups began right after I received your reply. I don't know if I changed something or not, but it appears to be working now. Strange because they hadn't been working for about a month. It's a strange one! Thanks for looking into it for me.
