### ISSUE TITLE
Backup /2e files

### ISSUE THREAD

**Issue by acertain** [SimpleServer/SimpleServer#119]
My backed up `.DS_Store` file gets turned into `/2eDS_Store`(same contents) and a `/2e_permissions.xml` file gets created containing a resource fork.  Also, shouldn't the world folder be in a world folder instead of the root directory of the extracted folder? A .AppleDouble folder also gets created in each directory containing a copy of all of the files in the folder its in but this may just be a The Unarchiver or afp error.

**Comment by heapoutofspace** [comment]
The whole /2e thing comes from afp, I have this problem too. The world folder needs to be there for other tools like WorldEdit.

We should meet in our IRC channel to discuss all these things after I get home. iPhone in McDonalds isn't very productive :D

**Comment by acertain** [comment]
But, how do those tools need to access the backups?

**Comment by heapoutofspace** [comment]
They expect ziped world folders named exactly how they are now. Therefor Any changes to our system need to be optional.
