### ISSUE TITLE
Cannot set up commands with two slashes

### ISSUE THREAD

**Issue by liamzdenek** [SimpleServer/SimpleServer#120]
I can't set up commands with two slashes at the beginning, like WorldEdit commands- //wand, etc.

**Comment by acertain** [comment]
what have you tried? what do you mean by set up? we cannot fix it if we do not know what the problem is...
Have you tried logging in with a user in a group with `forwardUnknownCommands=true`

**Comment by liamzdenek** [comment]
I have tried that. And it works just fine. //wand worked with forwardUnknownCommands=true but with name="/wand" (i assume it prepends a "/") doesn't work.
