### ISSUE TITLE
simple server not fully initializing

### ISSUE THREAD

**Issue by Aest47** [SimpleServer/SimpleServer#121]
when i try to start simple server it loads up to the recipes and achievements and then stops. runs perfectly fine on my other comp using copy and paste files and settings. here is what it loads. any ideas?

SimpleServer -- Copyright (C) 2011 SimpleServer authors (see CONTRIBUTORS)
This program is licensed under The MIT License.
See file LICENSE for details.

> > Starting SimpleServer 8.2.3 stable
> > 151 recipes
> > 16 achievements

**Comment by acertain** [comment]
can you give us some specs(of your computers involved)?

**Comment by Aest47** [comment]
its fairly old. its running win xp prof with a 2.80ghz intel celeron processor and 2030MB ram

**Comment by heapoutofspace** [comment]
Try pressing the return key when it freezes.

**Comment by acertain** [comment]
see https://github.com/SimpleServer/SimpleServer/issues/44

**Comment by Aest47** [comment]
k that helped a lot. it took a tad more convincing to get the thing to fully start but now im getting an issue with it creating a lot of new files with "conflicted copy" in the name

**Comment by heapoutofspace** [comment]
Are you running it in a dropbox folder?

**Comment by Aest47** [comment]
ya i am actually

**Comment by heapoutofspace** [comment]
Then you should tell dropbox to ignore the folder. It adds those conflict files because it can't keep up with the speed minecraft changes files.

**Comment by Aest47** [comment]
oh well thats good that its not another problem with me trying to run the server on that computer. i want to keep myself away from the console but i want to still be able to modify the server property files remotely. any suggestions how to do that better?

**Comment by heapoutofspace** [comment]
You can tell Dropbox exactly which files to sync. Only enable the simpleserver folder and the simpleserver.properties file in the root folder and you should be fine.

**Comment by Aest47** [comment]
sounds great. thank you very much for the help
