### ISSUE TITLE
Custom server.properties commands

### ISSUE THREAD

**Issue by Raptor2213** [SimpleServer/SimpleServer#129]
Some mods (such as [MineQuery](http://forums.bukkit.org/threads/dev-minequery-1-5-a-query-server-that-responds-with-server-info-1060.1358/) do not use a normal config file for important commands (such as the port they reside on).  

Instead, they use the server.properties file to set a variable, and SimpleServer does not allow the server.properties file to be edited, as it will simply overwrite it.  

To compensate for this bad programing could SimpleServer have a section where it passed down commands manually to the server.properties file?  (Much like the java arguments)

**Comment by dola** [comment]
The _server.properties_ already works in a way that it only overwrites the options needed by SimpleServer.
So if you create a line `minequery-port=25566` in the _server.properties_ is is not overwritten by SimpleServer and can be used by MineQuery. (It maybe is moved since SimpleServer orders all option alphabetically everytime they're written)

So simply ignore the warning this time and add the line to the _server.properties_ file...

**Comment by Raptor2213** [comment]
Ok, then I guess it's not passing it through properly.  

I may be miss-remembering the last time I tried this, but it still doesn't open the port properly, even if you do stick that line in there.  Test it yourself, and you'll see what I mean.  Yes, I did open the port for my router.

**Comment by dola** [comment]
I just tested it out and it seems to work for me.

You should see a line like this
`2011-08-29 01:02:04 [INFO] Starting Minequery server on 127.0.0.1:12345`
in the console when you start your server.

I even tested the server information query via telnet and it seems to work without any problems.
See here: http://d.pr/KtoQ
(left part is test, middle is server console with the note that Minequery started on the 3rd _[INFO]_ line, right is _server.properties_ with the `minequery-port` line)

Notice that you have to use a port that isn't in use already. It won't work if you use the same port for incoming players and for _Minequery_... And as you said you have to forward it correctly through your router. The mest is to simply retry the whole thing, maybe it didn't work before properly and now does.

**Comment by Raptor2213** [comment]
Yup, got that.

2011-08-28 17:55:32 [INFO] Starting Minequery server on 127.0.0.1:25560

Still not connecting to it though, perhaps there is another issue, I've now tripple-checked the port is, in fact, open.

**Comment by dola** [comment]
maybe the port is still blocked in your machines firewall. (not the router)
Are you using [this](http://minestatus.net/minequery/test) to test if _Minequery_ is accessible by Minestatus?

You can test if it works locally (so if it does you're really sure that it's something with a firewall or a wrong port forwarding). Simply open the commandline (windows: cmd, unix: terminal) and type in `telnet localhost 25560` if the server is running. Afterwars type `QUERY` and you should get an output similiar to the one I got in the screenshot above if it works.

**Comment by Raptor2213** [comment]
Telnet works, for some reason the site doesn't.  I guess it's retarded?

Anyway, thanks for the help.
