### ISSUE TITLE
Change IP for hamachi?

### ISSUE THREAD

**Issue by itusvirus** [SimpleServer/SimpleServer#133]
For some reason a friend cant connect to my server from his home. Hamachi servers work fine in the default server app. I like SimpleServer commands better so we would love to use this SimpleServer app. But changing the ip in the simpleserver properties file doesnt work. it just reverts back to 0.0.0.0. why and how do I fix this for gaming via hamachi?

or is there a way to get the commands used in SimpleServer in the default minecraft server app?

**Comment by dola** [comment]
You most likely forgot to shut down your server before changing the settings.
So try it again by first stopping the server (use `stop` in the console), then edit the _simpleserver.properties_ and lanuch the server again. It should work with hamachi in the same way as vanilla server does, so there shouldn't be any problems.

**Comment by acertain** [comment]
just keep it at default...it should work

**Comment by dola** [comment]
True too:

> just keep it at default...it should work
