### ISSUE TITLE
1.8 compatibility

### ISSUE THREAD

**Issue by dola** [SimpleServer/SimpleServer#138]
according to [this](https://gist.github.com/a4be5ddce802e177f366)

**Comment by dola** [comment]
basically works for now. If someone wants to test it use [this built version](http://cl.ly/0C0c040m2H220I160212).

**Comment by dola** [comment]
Left works:
- I assume that some parts of the nbt player files changed too. -> to be adapted
- add a `gamemode` attribute to the groups in _config.xml_ to set default gameMode.

**Comment by heapoutofspace** [comment]
```
add a gamemode attribute to the groups in config.xml to set default gameMode.
```

The game mode is already saved in the player file, do we really want to override that behavior?

**Comment by acertain** [comment]
Well, the gameMode should used unless it is manually changed...

**Comment by slvlirnoff** [comment]
I did compile the actual "git clone" and it seems to work well with 1.8 I had to incr the version number in the Bot.java source file to make the /warp work, and I had some issues with configuration (but that seems related to the recent changes of configuration system), otherwise it seems quite stable and working as expected in 1.8.

Good work !

**Comment by heapoutofspace** [comment]
I think the version number in [Bot.java](https://github.com/SimpleServer/SimpleServer/blob/master/src/simpleserver/bot/Bot.java#L39) is in fact correct. Maybe you didn't use the latest version.

Thanks for the feedback :)

**Comment by slvlirnoff** [comment]
VERSION should be 17, not 16 for the real 1.8 update (not the pre-x). It was working with the pre1 and pre2, but not with the final 1.8.

**Comment by heapoutofspace** [comment]
You're right, I assumed since there were no changes in the protocol the version would be the same.
