### ISSUE TITLE
After Config.xml <!-- Groups --> edit. 

### ISSUE THREAD

**Issue by Zedifus** [SimpleServer/SimpleServer#144]
Hey, just recently downloaded SimpleServer and was changeing the config.xml, now when i try to Start i get this error message... Any explanation/ help would be much appreciated. Here is the Syntax and error below.

Syntax:

```
<!-- Groups -->
<group id="0" name="Guest" color="f">
    <warmup>5</warmup>
    <cooldown>60</cooldown>
    <showTitle/>
</group>
<group id="1" name="Builder" color="a"/>
    <warmup>5</warmup>
    <cooldown>60</cooldown>
    <showTitle/>
</group>
<group id="2" name="UberBuilder" color="9"/>
    <warmup>5</warmup>
    <cooldown>60</cooldown>
    <showTitle/>
</group>
<group id="3" name="Mod" color="1">
    <ignoreChestLocks/>
    <showTitle/>
</group>
<group id="4" name="Admin" color="6">
    <ignoreChestLocks/>
    <ignoreAreas/>
    <showTitle/>
</group>
<group id="5" name="Owner" color="4">
    <ignoreChestLocks/>
    <ignoreAreas/>
    <showTitle/>
</group>
```

---

SimpleServer -- Copyright (C) 2011 SimpleServer authors (see CONTRIBUTORS)
This program is licensed under The MIT License.
See file LICENSE for details.

> > Starting SimpleServer 8.3.2 beta
> > [SimpleServer] Error in config.xml: org.xml.sax.SAXException: Found unknown tag
> > "showTitle"
> > [SimpleServer] Syntax error in comfig.xml! Config was not reloaded.
> > Exception in thread "SimpleServerListener" java.lang.NullPointerException
> >         at simpleserver.Server.loadResources(Unknown Source)
> >         at simpleserver.Server.startup(Unknown Source)
> >         at simpleserver.Server.access$400(Unknown Source)
> >         at simpleserver.Server$Listener.run(Unknown Source)

---

**Comment by heapoutofspace** [comment]
```
<group id="2" name="UberBuilder" color="9"/>
    <warmup>5</warmup>
    <cooldown>60</cooldown>
    <showTitle/>
</group>
```

should be

```
<group id="2" name="UberBuilder" color="9">
    <warmup>5</warmup>
    <cooldown>60</cooldown>
    <showTitle/>
</group>
```

(Only empty elements have a slash before the closing `>`)

**Comment by Zedifus** [comment]
ohhhhh thank you for the speedy reply, sorry I feel abit stupid now, rookie mistake :$ 
Thanks again for your help :)
