### ISSUE TITLE
Unidentified users bypassing the whitelist

### ISSUE THREAD

**Issue by Kerrus** [SimpleServer/SimpleServer#145]
Earlier today three users not on our whitelist logged on to our server and began griefing. Our whitelist is enabled, and the server is in online mode. We are using version 8.3 and everything has otherwise been working.

Once we discovered these users were not on our whitelist, we banned them as standard procedure- but I'm still concerned that they got on in the first place. 

Any help would be appreciated.

**Comment by acertain** [comment]
Seems like a bug to me, verified config and stuff on irc

NOTE: hes with jestservers and a dedicated game server :( may be a problem there, also the ppl who bypassed actually got their server(s) removed from jestservers

**Comment by heapoutofspace** [comment]
Sounds serious, I will check if this feature works tomorrow. (With tomorrow I mean after sleeping, it is 5:42am)

**Comment by heapoutofspace** [comment]
As promised, I [fixed](https://github.com/SimpleServer/SimpleServer/commit/994e40b762f7e7ad2494037306c1755329efeca6#L4L180) it and will release an update later today.
