### ISSUE TITLE
No such command /rename

### ISSUE THREAD

**Issue by kyborek** [SimpleServer/SimpleServer#147]
I just wanted to use /rename command because its very important for me but simpleserver doesnt know command /rename it just says "No such command /rename kyborek test". However in online commands list there is /rename and also /help rename works...
Please fix the rename function. Thank you very much

**Comment by heapoutofspace** [comment]
This command is not in the config by default because our current method still has some flaws. If you still want to use it just add the following line to your _config.xml_ file:

```
<command name="rename" allow="5+" />
```

**Comment by kyborek** [comment]
Okay thank you, i will better wait for official release of this command.
