### ISSUE TITLE
New commands don't get added to command permission list

### ISSUE THREAD

**Issue by heapoutofspace** [SimpleServer/SimpleServer#15]
New commands should be added with their standard permissions after an update. The admin should be notified in the console, so he can change the permission the way he wants it. 

The same goes for give-alias-list.

**Comment by apirogov** [comment]
You really want this for 8.0? I'm not sure I can do it this until Friday (would require a rather long coding session to get this in permissions.xml, is not a "quick fix")

**Comment by heapoutofspace** [comment]
For the 8.0 release it should be enough if you just hardcode the !myarea. For the give-alias-list I would just check the default if something isn't defined by the user. If you don't think you can that it's ok, I can try it myself or we can do it for 8.1.

**Comment by apirogov** [comment]
For give-alias-list it shouldn't be a big problem as it's also a
Properties-based config, load doesn't reinit the hash, but just adds
stuff ... thats the way I think it works in simpleserver.properties...

Not a big deal hardcoding the addition of area and myarea into the
converter script, if that is what you want now...

But for the real solution it's quite some work as it requires to have
2 instances of permissionConfig loaded, cause using config.load over a
loaded config will most likely make problems in the best case and
break the whole config in the worst case... so the
getCommandPermissions function would have to check whether a command
not found in the config might be in the defaults and if yes, create
that entry in the real thing... and its again some steps more than
config.put("name","value") and error prone as I can only see on
runtime whether those xpaths etc are all working fine... So it's not a
difficult but time consuming task to get this done...

**Comment by heapoutofspace** [comment]
Maybe we should put this aside until we have a working updater. It would be a lot faster n lighter if these kind of things only are done when updating. 

I still think myarea should be hardcoded to make the transition to 8.0 easier.
