### ISSUE TITLE
I cant find this feature... is it in SS or will it be a future feature?

### ISSUE THREAD

**Issue by Zedifus** [SimpleServer/SimpleServer#152]
Weather control... the rain really annoys me and i was looking through the commands for summin like /weather set clear
like /time set day.

If someone could clue me in, that would be much appreciated, thankies :)

**Comment by dola** [comment]
currently it's not possible for SimpleServer to take real control of the weather.

the way SimpleServer works doesn't allow real handling of weather, but we were already discussing about some solutions that would only make the client think it's a specific weather, what would have the disatvantatge, that for examle if there is a thunderstorm mobs spawn but the player sees sunny weather...
