### ISSUE TITLE
forwardonly=true wont work

### ISSUE THREAD

**Issue by acertain** [SimpleServer/SimpleServer#158]
i think this is a bug for all of us...

**Comment by The-PC-Tech-Guy** [comment]
Agreed, must fix the dtd file that is hard-coded into SimpleServer's parser... Kind of lame that it's hard-coded, especially when their already is a URL in the XML file.

**Comment by acertain** [comment]
I dont think the DTD is the problem here, but that must be fixed to

**Comment by The-PC-Tech-Guy** [comment]
Well that's what I get when I put it through an XML parser. I get a similar message on the console as well.

**Comment by heapoutofspace** [comment]
You might be right, I forgot to put that in the DTD.

**Comment by heapoutofspace** [comment]
Also it isn't "lame" that the DTD is hard coded, nobody should be able to change it.

A workaround for the problem is to set xmlInlineAttribute to false.
