### ISSUE TITLE
instant destroy

### ISSUE THREAD

**Issue by acertain** [SimpleServer/SimpleServer#162]
just remove it...

**Comment by heapoutofspace** [comment]
I already removed it from the config.xml...

**Comment by acertain** [comment]
but the command still exists...

**Comment by heapoutofspace** [comment]
So what? Maybe someone still wants to use it (mining is not instant but faster...)

**Comment by acertain** [comment]
but creative mode exists...

**Comment by heapoutofspace** [comment]
But creative mode includes other things like flying and infinite items. There are already users asking me how to enable only one of those features...

**Comment by acertain** [comment]
i think if that is possible do it, and delete this...

**Comment by The-PC-Tech-Guy** [comment]
Well let's just keep it in there, not quite as an Easter egg but as a memory of the SimpleServer long ago :D Plus I'd rather focus on other things -- those who know this command most likely know it is now broken... somewhat...

**Comment by acertain** [comment]
well, add a it is broken to teh /help idbehold

**Comment by The-PC-Tech-Guy** [comment]
Well, Sadimusi should have removed it from the /help menu though. Or that should be hidden by default... but at least we can hide it ourselves if needed.

**Comment by heapoutofspace** [comment]
It is hidden by default and shouldn't even show up in `/help`

**Comment by sk9c00** [comment]
its like god mode... In creative it ruins some of the survival features...

**Comment by acertain** [comment]
its broken...
