### ISSUE TITLE
custAuth, onlineMode config disappears

### ISSUE THREAD

**Issue by eskwayrd** [SimpleServer/SimpleServer#163]
Hi,

I'm trying to run SimpleServer 8.3.3 on Windows 7 after having last used it about 6 months ago.

It seems to run just fine, but I'd like to allow non-authenticated clients on my local network to join.

Whenever I add custAuth=true and/or onlineMode=false to simpleserver.properties, those config lines get removed when SimpleServer starts up.

When non-authenticated clients attempt to connect, they get the message: Failed to login: user not authenticated
and the log contains: Disconnecting frpm IP:PORT: Protocol Error

Solutions, or ideas to try?

Thanks.

**Comment by dola** [comment]
That's most likely because those two properties were moved into the new config.xml file with 8.3. Now only options that really have to be set on startup arw in the simpleserver.properties. The others can now be changed while the server is running and reloaded with the reload command.

**Comment by eskwayrd** [comment]
Ah. That makes sense. I was following the custom authentication docs, which specifically states that custAuth=true should be placed in simpleserver.properties. Obviously, the docs are out of date.

I wonder if a config.xml example could be added to the docs?

**Comment by dola** [comment]
ah true. sorry for that.
For the moment I think the default config.xml has to be enough. Maybe we can add an example with more specific configurations in some time.
