### ISSUE TITLE
[Bug]FreeBSD simpleserver.properties clearing itself!

### ISSUE THREAD

**Issue by thesymbol** [SimpleServer/SimpleServer#171]
When i use the /stop command the simpleserver.properties becomes empty (nothing left in the file).

any help would be appriciated.

in console it says:

[SimpleServer] java.util.NoSuchElementException: No line found
[SimpleServer] Minecraft process stopped unexpectedly!
[SimpleServer] Stopping Server...
[SimpleServer] java.io.InterruptedIOException
[SimpleServer] Could not write simpleserver.properties
[SimpleServer] Server stopped successfully!

using FreeBSD 7.3
SimpleServer 8.3.4 Stable

One question: why dose the server need to write to the simpleserver.properties?

**Comment by bryanburke** [comment]
This is a bug in the native FreeBSD port of Java. However, I can confirm that using the latest versions of the OpenJDK 6 and 7 fixes this issue.

**Comment by thesymbol** [comment]
I have used a script instead that have fixed the issue for me.
