### ISSUE TITLE
growl for teh web interface!

### ISSUE THREAD

**Issue by acertain** [SimpleServer/SimpleServer#178]
must mac users appreciate prowl and there is a php library for it :D

http://growl.laurent-laville.org/

in case you dont know what growl is:

http://growl.info/about.php

**Comment by heapoutofspace** [comment]
I am a Mac user and therefore know Growl ;)
Actually growl has nothing to do with the web interface, what would you exactly use it for?

**Comment by acertain** [comment]
well, there is a php library :D, so we could make a setting for notifications if a player joins, etc

**Comment by heapoutofspace** [comment]
The webinterface won't be written in PHP and even if it were it wouldn't be executed all the time to check the player list. Instead the server itself could push the growl notifications, the protocol is actually quite simple.

**Comment by acertain** [comment]
ah, well ill see how to do that...

**Comment by acertain** [comment]
what will the interface be in?  overseer is php...

**Comment by heapoutofspace** [comment]
It will be integrated in the server itself, so obviously Java.
