### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by regelneef** [SimpleServer/SimpleServer#181]
Hi i'm running a vanilla 1.8 server at the moment. And I'm having some strange login problems.
First of all, SS keeps telling me dat Minecraft is down... which is not the case, I checked :)
And then when I'm trying to login (onlinemode=true) I get prompted by the client "Protocol error".

When I then stop SS and just start minecraft_server.jar directly there are no issues.

So I was wondering is minecraft may have changed it verification-check of maybe SS is to sensitive to label minecraft.net offline while it's not?

**Comment by heapoutofspace** [comment]
Is your firewall blocking access to we servers without a host name? I think we put the host name in the newest version, so maybe updating to 8.3.4 helps.

**Comment by regelneef** [comment]
Oke I updated to 8.3.4, which changes nothing except for the fact that minecraft.net comes back online after a couple of minutes. and we can logon again.
Still this could be a minecraft.net problem and not SS. But the protocol error message threw me off course
