### ISSUE TITLE
Request: Specific warps command

### ISSUE THREAD

**Issue by JakeDiFebo** [SimpleServer/SimpleServer#182]
Hey, Simple Server!

I really, REALLY wish I could give people the opportunity to warp to cetain places, based on where they are standing.

I might be able to give them the opportunity to warp in an area with area-based permission...

But then anyone can go anywhere, and to fully apply the Groups/ranking system, different people should be allowed to go to certain places, am I right?

Thus, please design (and I will be your best friend):
•  a command for custom warps privelidges

**Comment by ChironXII** [comment]
You can do this via permissions for specific arguments: 

(command name="warp" allow="0+")
        (argument allow="4+")Admin's club(/argument)
        (argument allow="2+;chironxii")City(/argument)
    (/command)

Change the parentheses to brackets... sorry it wouldn't let me post it with them.
You can use the permissions the same way as you would any command. Make sure that you take the "/" out of the first command tag, as it won't work if you don't. (that one took me a while to find when I did it XD)

**Comment by JakeDiFebo** [comment]
OH MY GOODNESS. Thank you, thank you, THANK you! You're a life-saver! If you hadn't saved my life, I probably, would lose it, and end up having to stop playing minecraft and GET a life. :D Can't have that, now can we? ^_^
