### ISSUE TITLE
Updating minecraft_server.jar file.

### ISSUE THREAD

**Issue by sk9c00** [SimpleServer/SimpleServer#183]
Is it possible to make SimpleServer compatible with pre-releases?
Because the bot system which is the center pin of most of your commands doesn't work because of the outdated bot client...

Just wondering if it is possible to make a separate folder where we can update the minecraft.jar or minecraft_server .jar manually and get the wrapper to work from there... This would help a lot!!!

**Comment by heapoutofspace** [comment]
A new protocol version usually comes with protocol changes and won't fully work with old versions of SimpleServer. I already updated the protocol to 1.9pre3 and posted a build in the forum.

**Comment by sk9c00** [comment]
Where is the link exactly?

**Comment by acertain** [comment]
note: you need to manually dl the prerelease jar for minecraft_server

**Comment by sk9c00** [comment]
Couldn't you dedicate a specific for advanced users only folder where you can update the server protocols but I have to update everything else by myself... as in the minecraft_server.jar...

**Comment by heapoutofspace** [comment]
What exactly would be the benefit of this? Just bumping the protocol version would disconnect you all the time ;)

**Comment by sk9c00** [comment]
pre6 ready yet?

**Comment by heapoutofspace** [comment]
Teleporting won't work, but there were no actual [protocol changes](http://b.wiki.vg/1.9pre6...1.9pre5#packets). I won't make an update since the release candidate is coming out tomorrow.

**Comment by dola** [comment]
since 1.0.0 is out this is kind of obsolete.

**Comment by sk9c00** [comment]
With the new 11w47a and 11w48a versions out... There could still be random protocol changes...
I know there aren't much now, but it is still possible...

**Comment by heapoutofspace** [comment]
Thanks to [burger](http://b.wiki.vg/11w48a...1.0.0#packets) we know if there are any changes only seconds after a release. So don't worry about that.

**Comment by sk9c00** [comment]
I've already realised ages ago... but it would be useful to leave it open for other issues related instead of multiple issues...
