### ISSUE TITLE
gamemode causes disconnect if not 1 or 0

### ISSUE THREAD

**Issue by ChironXII** [SimpleServer/SimpleServer#187]
This isn't really a big deal, but using /gamemode will cause a disconnect if anything other than 1 or 0 is put after it. Didn't see this on here, so I thought I would let you know.

**Comment by dukevyner** [comment]
I confirm the issue, while its not a problem(as only 0 and 1 are in use) I tend to hit the wrong key and get booted

**Comment by bryanburke** [comment]
If this issue is fixed, can it be closed? We have way too many stale issues.

**Comment by kevinpeno** [comment]
@bryanburke I accidentally set an invalid gamemode the other day and was not kicked. I'm guessing @dola fixed it with the above.

**Comment by dola** [comment]
I never closed this because I didn't test it in detail. But I think it should be fixed like that.
