### ISSUE TITLE
add "why simpleserver" to faq

### ISSUE THREAD

**Issue by acertain** [SimpleServer/SimpleServer#188]
for ppl that don't get why simpleserver is worth using vs bukkit plugins, etc.

**Comment by mensreaMC** [comment]
I could answer this quite simply:

"Simple server is, as its name implies, simple to use. Easy to setup and maintain with a low barrier to entry. You don't have to take an afternoon off to learn how to use this system. Simple server is a one stop shop for chat functions, area protection, commands, and group functions that rival those you might find in bukkit (but with none of the hassle). Its functionality grows with each version. Even better, simple server is the perfect server manager for admins who use mods that are not ported to bukkit."

**Comment by acertain** [comment]
they don't rival those in bukkit.....but that is pretty good...

**Comment by dola** [comment]
Thanks for this. Added it to the faq.
