### ISSUE TITLE
Craftbukkit Problem

### ISSUE THREAD

**Issue by BigBrick** [SimpleServer/SimpleServer#193]
Craftbukkit isn't accepting commands from my users and can't display anything. Also, my console chat isn't visible to players either. It works fine itself, all of my plugins work; its just that some of them aren't accepting commands from ingame.

**Comment by heapoutofspace** [comment]
Did you activate forwardUnknownCommands for your group? You should take a look at our [Bukkit guide](https://github.com/SimpleServer/SimpleServer/wiki/Bukkit).

**Comment by BigBrick** [comment]
Its not the commands I'm particularly saddened by, its the fact that bukkit can't display anything to my users.

**Comment by BigBrick** [comment]
I think I fixed it; hurray for fresh installs!
