### ISSUE TITLE
Minecraft Update 1.0 --> Exception "ServerStream-USERNAME"

### ISSUE THREAD

**Issue by QueerCodingGirl** [SimpleServer/SimpleServer#196]
The logfile with replaced username, ip and removed timestamps:

> [SimpleServer] IP Connection from xxx.xxx.xxx.xxx!
> [INFO] USERNAME [/127.0.0.7:36885] logged in with entity id 204 at (204.6875, 66.0, 176.46875)
> Exception in thread "ServerStream-USERNAME" java.lang.IndexOutOfBoundsException
>        at java.io.DataInputStream.readFully(DataInputStream.java:175)
>        at simpleserver.stream.StreamTunnel.readUTF16(Unknown Source)
>        at simpleserver.stream.StreamTunnel.handlePacket(Unknown Source)
>        at simpleserver.stream.StreamTunnel.access$300(Unknown Source)
>        at simpleserver.stream.StreamTunnel$Tunneler.run(Unknown Source)
> [SimpleServer] java.io.EOFException
> [SimpleServer] PlayerStream error handling traffic for xxx.xxx.xxx.xxx (b)
> [SimpleServer] Socket Closed: xxx.xxx.xxx.xxx
> java.net.SocketException: Connection reset
> java.net.SocketException: Broken pipe
> [INFO] USERNAME lost connection: disconnect.genericReason

I think no explaination is needed. ;)

**Comment by dola** [comment]
You most likely didn't use the newest version of SimpleServer that should be compatible with 1.0.0. Have a look at the [forum](http://www.minecraftforum.net/topic/309373-software-simpleserver-wrapper-834181/) where you can find a link to a build for 1.0 rc2 (should work for the official release too)
