### ISSUE TITLE
SimpleServer not playing nice with McBans

### ISSUE THREAD

**Issue by Raptor2213** [SimpleServer/SimpleServer#197]
Even when in online mode in the SimpleServer xml file, McBans thinks that the server is running in offline mode.  

This is because SS sets the server.properties file to offline mode.

**Comment by Raptor2213** [comment]
Attempted workarounds:

Attempted to set the server.properties file to read-only.  Server fails all logins, McBans does load.
Attempted to set the server.properties file to read-only and xml information to offline mode. Server fails all logins, McBans does load.

**Comment by acertain** [comment]
open w/ #131

**Comment by Raptor2213** [comment]
Closing - duplicate issue.  Copied additional info to 131.
