### ISSUE TITLE
Area user permissions for two

### ISSUE THREAD

**Issue by GregoriMarow** [SimpleServer/SimpleServer#206]
hi (Using RC 8.4 for 1.0.1)

I tried to add a additional user to an good working area. Here the example:
`<area name="Castle" start="410,0,701" end="625,127,529" owner="-">
            <allblocks place=";testusera" destroy=";testusera" use="*"/>
            <chests allow=";testusera"/>
 </area>`
So i want also that testuserb can build in this area, so i did it like that:
place=";testusera;testuserb"
but it will reseted after startup.
I tried different possibilities with , ; <> to seperate the names. But it will be resetet or generates an error.
please help, thanks

**Comment by bryanburke** [comment]
Did you try editing the config file while the server is running and then typing "reload" into the console or "/reload" as a privileged player?

**Comment by GregoriMarow** [comment]
I stoped the server entered the new value, started the server and the new user was automaticly removed. I also tryed it in running mode. opend xml, entered the additional user, saved and enterd the reload command into the console. And again the new user was removed.

Befor: place=";testusera"
after editing and saving: place=";testusera;testuserb"
after starting server again place=";testusera"

So after the restart or reload of the server the second added user where reseted.

Its very confusing. Is there anything incorrect in my syntax?

( I have some experience in editing xml's of the cry Level file from crysis, so i have some basic skills ;) )

**Comment by GregoriMarow** [comment]
Well if its not working i have to change to bukkit and residence mod. 
My players are asking me every day: "Can we have build permissions for two or more players" and i can just answer, that i am waiting for support :(

Please help

**Comment by heapoutofspace** [comment]
As you can see in the [wiki](https://github.com/SimpleServer/SimpleServer/wiki/config.xml#wiki-permission-syntax) the correct syntax would be

```
;testusera,testuserb
```

**Comment by GregoriMarow** [comment]
Many Thanks

Well you mean this here:
`players := <playerEntry> | <playerEntry>,<players>`

I have read this part well over 10 times and haven't seen this dam comma. Sry
