### ISSUE TITLE
Thread error on login: java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by kevinpeno** [SimpleServer/SimpleServer#207]
Trying to add my current world with this wrapper. I've left pretty much everything as default, but I can give my config files too if needed. Here's the console output.

```SimpleServer -- Copyright (C) 2011 SimpleServer authors (see CONTRIBUTORS)
This program is licensed under The MIT License.
See file LICENSE for details.

> > Starting SimpleServer 8.3.4 stable
> > 174 recipes
> > 27 achievements
> > 2011-12-11 14:23:57 [INFO] Starting minecraft server version 1.0.1
> > 2011-12-11 14:23:57 [INFO] Loading properties
> > 2011-12-11 14:23:57 [INFO] Starting Minecraft server on 127.0.0.1:25566
> > 2011-12-11 14:23:57 [INFO] Preparing level "world"
> > 2011-12-11 14:23:57 [INFO] Default game type: 0
> > 2011-12-11 14:23:57 [INFO] Preparing start region for level 0
> > 2011-12-11 14:23:58 [INFO] Done (858114998ns)! For help, type "help" or "?"
> > [SimpleServer] Wrapper listening on 0.0.0.0:25567 (connect here)
> > [SimpleServer] Note: 0.0.0.0 means all IP addresses; you want this.
> > [SimpleServer] IP Connection from 127.0.0.1!
> > [SimpleServer] IP Connection from 127.0.0.1!
> > 2011-12-11 14:24:04 [INFO] bbqsamich [/127.0.0.3:57192] logged in with entity id 165 at (-49057.25, 71.0, -50016.3125)
> > [SimpleServer] Socket Closed: 127.0.0.1
> > Exception in thread "ServerStream-bbqsamich" java.lang.NegativeArraySizeException
> >         at simpleserver.stream.StreamTunnel.readUTF16(Unknown Source)
> >         at simpleserver.stream.StreamTunnel.handlePacket(Unknown Source)
> >         at simpleserver.stream.StreamTunnel.access$300(Unknown Source)
> >         at simpleserver.stream.StreamTunnel$Tunneler.run(Unknown Source)
> > [SimpleServer] java.io.EOFException
> > [SimpleServer] PlayerStream error handling traffic for 127.0.0.1 (a)
> > [SimpleServer] Socket Closed: 127.0.0.1
> > java.net.SocketException: Socket closed
> >         at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
> >         at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
> >         at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
> >         at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
> >         at java.io.DataOutputStream.flush(DataOutputStream.java:123)
> >         at wv.run(SourceFile:104)
> > 2011-12-11 14:24:36 [INFO] bbqsamich lost connection: disconnect.endOfStream
> > 
> > ```
> > ```

**Comment by bryanburke** [comment]
It looks like you're using the old version of SimpleServer (for Minecraft 1.8.1) with Minecraft 1.0.1. You can download the release candidate for Minecraft 1.0.1 at http://cl.ly/CK31

**Comment by kevinpeno** [comment]
Thanks, I'll look into that. If you had build instructions, and the rc version tagged, I'd prefer to build from the latest and help where I can :)

**Comment by mattymatny** [comment]
I also get this problem even when running on the latest version. I should also point out that i run a modded server/client. My mods have never had any issues with simple server before. Now with the Minecraft 1.0/1.0.1 releases it has this issue. I will also leave you with the following info that may help figure this out. My game runs fine and lets people in and out of the server and it runs fine with most of the custom content. I have however added Redstone Armor/Weapons/Tools, these seem to be the only ones that cause the problem. If a player interacts in any way (picks up/sees in chest) one of these redstone items then the server generates the above error and the next time they log in they fall through the world. FYI the modded server/client runs fine when not using simple server so there is no issue with the code on my end.

**Comment by heapoutofspace** [comment]
The items you have problems with are probably enchantable and therefore not handled correctly by the proxy. If you have [ant](http://ant.apache.org/) installed you could add the items manually to the [StreamTunnel](https://github.com/SimpleServer/SimpleServer/blob/master/src/simpleserver/stream/StreamTunnel.java#L63) and then compile it. I am working on a better solution for this problem, but that might take a while.

**Comment by mattymatny** [comment]
Cool I already added my stuff to the EnchantCommand file. I'll try
this one as well. Thanks for the tip, I will let you know how it turns
out.

Sent from my iPhone

On Dec 15, 2011, at 5:59 AM, Simon Marti
reply@reply.github.com
wrote:

**Comment by mattymatny** [comment]
So adding them to both the EnchantCommand file and the StreamTunnel file fixed my problem. Thanks for the help.

**Comment by bryanburke** [comment]
@kevinpeno I agree we need to have current versions tagged. We also need more documentation on the wiki for developers (see Issue #210), including build instructions.

Please close this issue if all problems have been satisfied.

**Comment by kevinpeno** [comment]
@bryanburke I was done when I found the solution. I left it be because of the conversation afterwards. I've since found the appropriate way to build from source and am doing my best, as evidence in my posts here, to get involved in the product now.
