### ISSUE TITLE
Chests are not protected inside of an "area".

### ISSUE THREAD

**Issue by SeeJayEmm** [SimpleServer/SimpleServer#21]
I updated to 8.0.4 today and was very intrigued by the area feature.  The only problem I'm seeing is that even tho, I believe, it is configured properly (I just setup an area using the /myarea command) people can still open and manipulate the chests within.

The protection vs block changes and using things such as doors, workbenches, & furnaces all appear to work.

**Comment by dola** [comment]
fixed through [this commit](https://github.com/SimpleServer/SimpleServer/commit/814da3a32c85e11b7d7f1132aa48d125fd61d285) by sadimusi.
