### ISSUE TITLE
Technic Pack

### ISSUE THREAD

**Issue by ulfsarkhuskarl** [SimpleServer/SimpleServer#213]
Hello, I am running a server with the Technic Pack mod, http://technicpack.net for now it is currently 1.8.
My issue here is that: When I launch the server without "SimpleServer" everything is fine without any errors and that. When I launch it with "SimpleServer" and I log in, my character falls through the ground endlessly without dying or anything, but I can see the mobs (zombie, etc). Yes I used the 'SimpleServer' for 1.8. I also read the compatibility with the mods, I also tried running only IndustrialCraft, same effect. What am I doing wrong?

Regards.

**Comment by dola** [comment]
SimpleServer only supports mods that are specially considered in the network proxy. (see [SteamTunnel.java](https://github.com/SimpleServer/SimpleServer/blob/master/src/simpleserver/stream/StreamTunnel.java))
I never used TechnicPack myself but as it looks, it is a collection of many mods at the same time an therefore we would have to consider each of them seperately (especially their special network packets) to make SimpleServer compatible with them.

If you want to (and know Java a bit) you could try it yourself by adding each additional packet the mods use to the StreamTunnel file. However you do have to inspect each mod itself for new packets (or see if they have some documentation about it anywhere)...

**Comment by ulfsarkhuskarl** [comment]
Alright, I thank you for your support.
