### ISSUE TITLE
Colored MOTD

### ISSUE THREAD

**Issue by bryanburke** [SimpleServer/SimpleServer#216]
I would like to look into adding color support to the MOTD system. My main reason for wanting to do this is to allow cave/nether mapping in Rei's Minimap: http://www.minecraftforum.net/topic/482147-100b181b19pre5dec12-reis-minimap-v29/

Can one of the maintainers take a look at the instructions on enabling cave mapping on that forum thread? You guys are much more familiar with the ins and outs of SimpleServer than I am. Thanks.

**Comment by dola** [comment]
SimpleServer already supports color codes (even in the motd). But unlike bukkit it uses (the vanilla like) § in place of & to indicate a color code. So you should be able to use the examples of the forum thread you postes with all & replaced by §. Let us know if it works...
I myself don't know exactly how this plugin would be able to distinguish the motd from a normal chat message but maybe it inspects every chat message sent...

**Comment by The-PC-Tech-Guy** [comment]
Yeah, I don't think it counts SS MOTD as the MOTD, because when I tested it with Zombe's mod (without the color-code version), it did not work. I integrated it with the authentication plugin I was using.

**Comment by bryanburke** [comment]
I got it to work with Rei's Minimap. I put the following at the beginning of the first real line of text in my motd.txt:

```
§0§0§1§e§fWelcome to...
```

This enabled cave mapping. Note that putting the color codes on their own line won't work.

**Comment by dola** [comment]
Good :)

**Comment by sk9c00** [comment]
It seems to be broken... Cos I keep on getting:
§0§0§1§e§fWelcome to...
=[?]0[?]0[?]1[?]e[?]fWelcome to...

**Comment by Traxis** [comment]
Indeed, it doesn't work with "§".

Edit: Ok, it works perfectly. You just need to save the file as UTF-8. I hope this helps anyone using Rei's Minimap with SimpleServer.
