### ISSUE TITLE
/unmute Does Not Work

### ISSUE THREAD

**Issue by Chase817** [SimpleServer/SimpleServer#218]
Once you mute a player, /unmute will not unmute them. Issuing the unmute command only unmutes the player "unmute." 

Ex: I issue /unmute Chase817    ------>     It will say "Player unmute has been unmuted!"

**Comment by kevinpeno** [comment]
I had the same pull I was going to request. Good on ya ravngr

**Comment by ravngr** [comment]
No problem, I still pretty new to using git and haven't got around to working out how to make a pull request for just a single commit. It's a pretty minor change so the devs can probably just integrate it :P
