### ISSUE TITLE
Multiple Groups

### ISSUE THREAD

**Issue by kevinpeno** [SimpleServer/SimpleServer#225]
I'd like to suggest the ability to have multiple groups. Since all permissions in the current system are deny unless assigned, it also makes inheritance possible and organic. Also, if done correctly, this might even resolve issue #194.

The primary use case I have so far is that I want moderators and admins to be able to talk in one channel (moderator group chat) while also maintaining their own groups (and group chat channel). I've had to set everyone in the moderator group and manually assign names to permissions I'd give admins (or myself as owner) to commands. It is quite tedious. If I could assign admins to the moderator group as well, then this would be far easier to manage.

Because having multiple groups could become quite complex, I think it would be necessary to expand the `/setgroup` command to a `/group` command that allows the ability to set, unset, list the groups that a user is in, and list who is in a named group. I also think it would be a good idea to use group/name as the identifier (case insensitive) instead of numbers to resolve what group is what.

**Example usage of new `/group` command:**
- List groups `/group list`
- Add a username to a group `/group <groupId> add <username>` -> `/group admin add kevinpeno`
- Remove a username from a group `/group <groupId> remove <username>` -> `/group admin remove kevinpeno`
- List members of a group `/group <groupId> members` -> `/group admin members`

**Comment by ravngr** [comment]
I like the idea but I don't think the current group system would work well with this, just because you would run into trouble both uniquely identifying groups (say for command permissions) and also allowing players to create/destroy as required. I'd suggest adding player groups or something; distinct from the current groups in that they are only used for chat and possibly area permissions (so you could have group constructions) and can be dynamically created by players.

**Comment by kevinpeno** [comment]
I don't see conflict for command permissions, since I talked about them above, specifically that all commands are whitelisted by allowing permission (though I realize that some are defaulted in the config). For example, exclude defaults for now, I have a moderator group that has `/tpto` permission and I have an admin group that has `/warptome` permission. The system should be able to determine, by virtue of allowance, that I have both commands available to me without breaking backwards compatibility (since no one has multiple groups yet). The only exception to this is that the 0+ (plus sign specifically) breaks since there is no concept of a group greater than another. However, given that is the only break I see so far, the config could be updated by the server on first run to support group "promotions" or you could just call it a BC break.
