### ISSUE TITLE
Protocol updates (1.1 -> 1.2)

### ISSUE THREAD

**Issue by bryanburke** [SimpleServer/SimpleServer#231]
This issue will be used to track all protocol changes leading up to the release of Minecraft 1.2. All pre-release protocol updates should be handled on a separate (non-master) branch, and this issue should be closed after complete compatibility with Minecraft 1.2 release is achieved.

Pre-release 12w04a updates protocol to version 24 (since 1.1), with the following changes:
- 0x18, server-to-client, +1 byte:
  1. int
  2. byte
  3. int
  4. int
  5. int
  6. byte
  7. byte
  8. byte
  9. metadata (handled by copyUnknownBlob())
- (New) 0x23, server-to-client:
  1. int
  2. byte

**Comment by bryanburke** [comment]
Updated protocol to version 24 (12w04a): 7c07aa04fd7181ac787369608450da3f89fb405b

**Comment by heapoutofspace** [comment]
Didn't you have to change the 0x02 packet at all? Someone in #mcdevs mentioned that the client now sends `name;host`...

**Comment by bryanburke** [comment]
Hasn't been fully tested yet; that's why these changes are on their own branch. I made the changes based on the latest information from the Minecraft Coalition website (b.wiki.vg).

**Comment by bryanburke** [comment]
@sadimusi Yep. Looks like Mojang changed the login hash, indeed. This is the error I am getting on the server:

```
java.io.IOException: Received string length longer than maximum allowed (26 > 16)
```

**Comment by heapoutofspace** [comment]
I guess you didn't notice [this](http://b.wiki.vg/about) ;)

And afaik it's not the login hash which has been changed but the username sent by the client.

**Comment by bryanburke** [comment]
And here I was this whole time thinking Burger Vitrine was a person.

**Comment by bryanburke** [comment]
I took a look at the way the StreamTunnel handles packet 0x02, and the code there doesn't seem to be the main issue. However, I failed to determine just how SimpleServer retrieves the incoming player's name. There are just too many moving parts there for me to handle, especially since I have schoolwork to do. Maybe someone else can jump in and edit the 1.2 branch. No real rush, after all.

**Comment by sk9c00** [comment]
Sounds so familiar, but just can't comprehend... I really would help if I could but my parents won't let me go any further into programming... :( All I can do is help with the Wiki and... Hmm... Just wondering If I'm allowed to update the README Files etc?
