### ISSUE TITLE
Coordinate based event polling / Event scripting system

### ISSUE THREAD

**Issue by apirogov** [SimpleServer/SimpleServer#238]
I will try to implement optional event polling.

Events will be defined in the config.xml and will (at least) allow to: show a message, teleport the player (to another player, a waypoint or coordinates) and give the player items. Each event may have a cool-down interval (to prevent spamming).

It will be a seperate thread which checks all defined event coordinates with the coordinates of all active players.

The use I intend will be to aid the creation of adventure maps.

In the future the event system might be extended to support rudimentary scripting (e.g. using events as toggles for other events, thus replacing buggy and complex redstone wiring in some situations)

**Comment by ravngr** [comment]
I did a similar thing in my branch to alert players when they entered/exited an area. I did it by adding an updatePosition to Player and doing my logig in there before passing the updated data to the Position object. Mostly in this commit 47f1ed48be6539d5dd214a87e936339eecb369c4 with maybe a minor tweak in subsequent ones. Nowhere near as comprehensive as what you want, but might give you a starting point.

**Comment by apirogov** [comment]
Thanks! This is quite a different approach than what I intended, maybe even "cleaner" ...

The idea with the automatic announcements is also nice! Are you going to push it upstream?

Your /pos command also does the same thing as my /warptoc... I wonder why such a command is still not in master, as its not a big thing to do...

**Comment by ravngr** [comment]
Previously I had done a similar thing with an extra thread that polled every second, I suppose it comes down to overhead of the thread versus the overhead of doing the check whenever the position is updated, although you could do my method with a time out or something if it really matters (it probably doesn't).

Yeah there are a couple of things I should push to the master I just either wanted to flesh them out fully and actually test it properly. If I find time soon I'll have a look through my code and see what's useful in the main repo.

**Comment by apirogov** [comment]
Ok the basic functionality I intended is done... you can check out my events branch if you like!

To test it, enableEvents has to be set to true and some event tags shall be defined like this:

  &lt;event name="somefunnystuff" coordinate="0,64,0"&gt;
  teleport #PLAYER 10,0,0
  say #PLAYER "Hello, world !"
   &lt;/event&gt;
  &lt;event name="itemspawner" coordinate="1,64,1" interval="10"&gt;
  give #PLAYER wood
  give #PLAYER cobblestone 10 
  &lt;/event&gt;

<b>Update:</b>
<a href="https://github.com/SimpleServer/SimpleServer/wiki/Events">Event System description</a>

<b>Update 2:</b>
The reference is complete... Some more ready-to-use examples may come soon :)

**Comment by apirogov** [comment]
Event system merged with master
