### ISSUE TITLE
Any way to import password?

### ISSUE THREAD

**Issue by Tarlafic** [SimpleServer/SimpleServer#239]
I'm going to change the server ,but I don't know which file the passwords in ,so is there any way to import password myself ?

**Comment by ravngr** [comment]
The passwords are stored in simpleserver.dat as a SHA1 hash with salt, use a tool like NBTedit to edit the hashes or copy them over to a new data file.

**Edit:** Like this http://imgur.com/li8gQ

**Comment by Tarlafic** [comment]
Very thanks.
