### ISSUE TITLE
Event feature

### ISSUE THREAD

**Issue by sk9c00** [SimpleServer/SimpleServer#241]
Is there an automatic rank up system in the events system... and is there an item take away event? And I'm not too sure, but do you have like an IF statement, like if you don't have the right items to take away, this event will not happen? 

If there is this function could someone give an example of the code?

**Comment by sk9c00** [comment]
Oh is there a "damage" item in hand or item in inv command? Like you press a button with a tool and it will damage it and give you something else?

**Comment by heapoutofspace** [comment]
RTFM

**Comment by sk9c00** [comment]
so what exactly is the auto rankup command in terms of event coding:
setgroup [player] [no]?
is there like a promote player up 1 group ladder system?

**Comment by heapoutofspace** [comment]
Again, [RTFM](https://github.com/SimpleServer/SimpleServer/wiki/Events). But I sugest you stay as far away from the event system as possible since you are clearly not experienced enough in programming/scripting.

**Comment by sk9c00** [comment]
I mean the format.... as in do I type directly the command or program with actual java keys...
