### ISSUE TITLE
Telnet feature

### ISSUE THREAD

**Issue by sk9c00** [SimpleServer/SimpleServer#242]
Could you try and imitate the telnet feature from this plugin?

http://forums.bukkit.org/threads/admn-remotetoolkit-r10-a12-restarts-crash-detection-auto-saves-remote-console-1-1.674/

**Comment by heapoutofspace** [comment]
There is already a telnet server built in.

**Comment by sk9c00** [comment]
But it doesn't seem to be compatible with my ipad 2 where as the other one does. Plus, there are no user accounts system, i.e. you can add other people to access as well with their own logins...

**Comment by heapoutofspace** [comment]
Telnet has absolutely nothing to do with iPads, but I can assure you that it works perfectly well on mine.

**Comment by sk9c00** [comment]
The problem is with 3 apps I used, SS telnet just kept on closing the connection or something.
But with remote toolkit, it doesn't do that...
