### ISSUE TITLE
SS COLOURING SYSTEM

### ISSUE THREAD

**Issue by sk9c00** [SimpleServer/SimpleServer#243]
Is it broken?
Cos I keep getting this:

§0§0§1§e§fWelcome to...
=[?]0[?]0[?]1[?]e[?]fWelcome to... In-GAME <--

**Comment by heapoutofspace** [comment]
It is not broken, you're file is probably just not utf-8 encoded.

also, stop shouting.

**Comment by sk9c00** [comment]
I'm using a mac, so unless there is some sort of mac UTF-8 encoding error... I don't thats the problem...

**Comment by heapoutofspace** [comment]
TextEdit sometimes messes up the encoding so make sure to save as UTF8.

**Comment by sk9c00** [comment]
Lol, I just realised that mistake... after I posted the last comment... SOZ for wasting your time... XD!!! I'm going to put this in the wiki now... lol...
