### ISSUE TITLE
/read command not working with Event execcmd

### ISSUE THREAD

**Issue by RadioRoscoe** [SimpleServer/SimpleServer#247]
The following event:

<event name="test" coordinate="-206,66,418">
        execcmd read
</event>

This should have output a list of documents, but gives this as output, "Document  does not exit". (note, there is an extra space between "Document" and "does"). When I add a document name to the read command, it also says that it does not exist, and seems to add a space after the doc name. Apparently some unprintable character is getting added to the argument?

**Comment by RadioRoscoe** [comment]
Sorry, I did not realize that the comments used Markdown, and part of my event code snippet above were lost. How do you keep the comment from stripping out xml code?

**Comment by heapoutofspace** [comment]
There's a manual for GitHub flavoured markdown [here](http://github.github.com/github-flavored-markdown/).

For code you can just use this:

``````
```` XML
<test />
````
``````
