### ISSUE TITLE
Additional permissions for /home command and OPs - request

### ISSUE THREAD

**Issue by lucifer6642** [SimpleServer/SimpleServer#250]
Would it be possible to code something so that OPs (or people with sufficient permissions in simpleserver config file) can use "/home _player_" without the player in question having invited them or set home to public.

It would be handy to police servers.

**Comment by apirogov** [comment]
@lucifer6642

Would it be okay if it was something like 

/home inspect player ?

Because then the sub-permission of inspect can be set seperately in the config.xml. inspect could be implemented just as a forced visit..

**Comment by lucifer6642** [comment]
That would be excellent. As long as it will work when player being inspected is offline

**Comment by lucifer6642** [comment]
I compiled Simpleserver from github repository 30 mins ago and gave it a test.

```
[SimpleServer] Bot Teleporter7797 died (Outdated server!)2012-04-24 18:34:56 [INFO] Disconnecting Teleporter7797 [/127.0.0.3:51251]: Outdated server!
```

This was with a fresh copy of Minecraft server 1.2.5.   Did you code it to only work with the snapshot release :( ?

**Comment by lucifer6642** [comment]
Just tested with snapshot 12w16a. Works fine there but unfortunately not in 1.2.5

Thanks for coding it in though, if you can't make it compatible for current version, will have to wait for new version of MC. Not using snapshots on my live server :)

**Comment by dola** [comment]
Yes I updated the protocol for the newest snapshot. 

You can easily make it compatible with 1.2.5 if you anyway know how to compile from source. Just change `VERSION` in [src/simpleserver/bot/Bot.java](https://github.com/SimpleServer/SimpleServer/blob/master/src/simpleserver/bot/Bot.java#L41) from _30_ to _29_ and compile it again.
Everything else does not affect the functionality with 1.2.5.

**Comment by lucifer6642** [comment]
Excellent, thanks

**Comment by lucifer6642** [comment]
Something gone wrong, whether its caused by this commit or another recent one, dunno. See issue 258
