### ISSUE TITLE
Event teleport command doesn't work above Y-Level 127

### ISSUE THREAD

**Issue by tazorax** [SimpleServer/SimpleServer#260]
It seems that the command teleport in event action doesn't work.

Messages are outputed but not the teleportation.

Example :
<event name="gotoBespin" interval="6">
        say #PLAYER "5"
        sleep 1000
        say #PLAYER "4"
        sleep 1000
        say #PLAYER "3"
        sleep 1000
        say #PLAYER "2"
        sleep 1000
        say #PLAYER "1"
        sleep 1000
        teleport #PLAYER 553,175,-1461
    </event>

teleport #PLAYER 553,127,-1461works

**Comment by apirogov** [comment]
Hmm weird, maybe the underlying implementation of teleport does not allow it... I'll look into this

**Comment by tazorax** [comment]
It's possible it's in relation with the #251 issue. I tried to compile master version yesterday but it seems it doesn't work with the 1.2.5 jar (too loog to log in)

**Comment by apirogov** [comment]
Well, in the current build (for the pre-release) I could not reproduce this, @tazorax might be right (about #251)... Should work from the next update on.
