### ISSUE TITLE
Question regarding event system

### ISSUE THREAD

**Issue by lucifer6642** [SimpleServer/SimpleServer#261]
Sorry if this is a dumb question.

I would like to set up an event so that every new player is given an item or kit.

Is there a way built into the event system to determine if it is a new player that has joined or would you have to define an array of players that stores whether they have received the "new player" item or not.

If the latter, does anyone have the time to write such a thing? I think it might come in useful to people.

**Comment by apirogov** [comment]
Just with the array... the code is:

```
    <event name="onPlayerConnect">
      if #VALUE #PLAYER Acontains not
          say #PLAYER "Welcome new player!"
          give #PLAYER wood

          set #THIS #VALUE #PLAYER Apush
      endif
  </event>
```

You see, it is just one new if expression within the player login event...
But this code exactly will just work in the next release (cause I added Acontains right now, kinda forgot it before)
