### ISSUE TITLE
Event scripting fails to handle non-SimpleServer commands or commands remapped by SS

### ISSUE THREAD

**Issue by ginbot86** [SimpleServer/SimpleServer#264]
I've been doing some work with SimpleServer's event scripting. I find that I cannot get it to execute commands if it's not native to SimpleServer, even if it's listed in config.xml or if ForwardUnknownCommands is set to "true". Also, using a command like "kill" causes it to use the SimpleServer version of the command, even if a plugin-based command provides different functionality with the same command name.

**Comment by apirogov** [comment]
The execcmd command uses the usual SimpleServer command execution and name resolving mechanism. So this should apply to SimpleServer as a whole - as far as I'm aware you can not decide which implementation of a command with the same name is to be used, as they are shadowed by each other as specified in the config... 

You just run a command as a player and rely on SimpleServer choosing the right one for you. Now execcmd does nothing different than this, just automated and ignoring all permissions.

I'm not using mods with SimpleServer, so please correct me if I'm wrong or give me an example how SimpleServer does not fail with this outside of event scripting...

**Comment by ginbot86** [comment]
Perhaps I should have clarified. What I mean is that even if a command entry is listed in config.xml and is configured so that <i>forwardOnly</i> is set to "true", the command still doesn't go through when using either <i>execcmd</i> or <i>execsvrcmd</i>; if a player does this manually, it works just fine. Same goes for if the <i>ForwardAllCommands</i> configuration value. Scripts won't execute non-SS commands no matter what command-forwarding parameters are set.

**Comment by apirogov** [comment]
Hmm this is strange indeed.. Are you using the official release from the downloads or the current developer snapshot for 12w17a?

because there changed a lot concerning events and it might be important to know whether it always has been broken or I may have broken it recently...

**Comment by ginbot86** [comment]
I'm running SS 8.4.3 for Minecraft 1.2.5 stable. I haven't tested the developer snapshot version yet.

**Comment by apirogov** [comment]
I tried to fix that problem in 1946bee7d2

I did some tests, but I don't think thats "real life"-like... so you can try the dev. version or wait for 1.3... hope this helps..
