### ISSUE TITLE
Bot Giver died when using TMI

### ISSUE THREAD

**Issue by Seraphli** [SimpleServer/SimpleServer#265]
I try to use TMI in game,using command like  give-command:/give {1}:{3} {2}
I can get dirt block.The command say /give 3:0 64.
But while using /give 6:3 64 ,nothing happen.
Server Console show this:[SimpleServer] Bot Giver77163 died (Unable to handle packet 0x2c after 0x0)
And I try to search on minecraftforum but can't find any solution.
But After I delete "world" folder and let server rebuild a new world,I can use TMI again.
I don't understand that.

**Comment by heapoutofspace** [comment]
SimpleServer uses bots to give items with metadata. Apparently you installed a mod that produces a protocol error when the bot connects. What mods do you have installed on the server?

**Comment by Seraphli** [comment]
I only installed UgoCraft. The official website is here:http://www.maocat.net/?page_id=4423
I thought it had something to do with a certain "world",because after I only changed "world" folder, the problem disappeared.

**Comment by heapoutofspace** [comment]
So you can give yourself 6:3 now?

**Comment by Seraphli** [comment]
Anything like [BlockID:Num] can't be given.The error will appear.
But [BlockID:0] can.

**Comment by heapoutofspace** [comment]
Does teleporting with /warp or /home work?

**Comment by Seraphli** [comment]
It has no problem with /tp.

**Comment by heapoutofspace** [comment]
And /warp and /home don't work? (/tp works completely different and has nothing to do with your problem)

**Comment by Seraphli** [comment]
I can set home and waypoint.

**Comment by heapoutofspace** [comment]
But you can't teleport to them?

**Comment by Seraphli** [comment]
yes.Pop up with this: [SimpleServer] Bot Teleporter46753 died (Unable to handle packet 0x2c after 0x0)

**Comment by heapoutofspace** [comment]
Normally either both players and bots work, or none of them. I never encountered your situation before but I assume it's UgoCraft's fault. Unfortunately I can't really do anything to fix it, it might start working again in 1.3.

**Comment by Seraphli** [comment]
But why the problem disappear in new world?I didn't remove the mod.

**Comment by heapoutofspace** [comment]
The problem was probably an item the bot dropped which wasn't handled correctly by SimpleServer.

**Comment by Seraphli** [comment]
Is there any possible that I can fix this problem without completely change the "world" folder?

**Comment by heapoutofspace** [comment]
What is not working apart from the give command? Can't you join the server anymore? You can try to remove only your player file in the world/players folder.

**Comment by Seraphli** [comment]
I can join my server.The problem still exist after I delete all player's date files.

**Comment by heapoutofspace** [comment]
What problem are you talking about? /give not working? Did removing the world folder fix that?

**Comment by Seraphli** [comment]
Yes...So I don't why.I said that before.
In my second comment:
I thought it had something to do with a certain "world",because after I only changed "world" folder, the problem disappeared.

**Comment by heapoutofspace** [comment]
I don't know what part of the world could be causing that. It might be a block or an item of some mod. You could try to travel far away and check if the problem still occurs there.

**Comment by Seraphli** [comment]
Well,actually your suggestion fix the problem.I don't know which part of "world" cause this problem.But I will try to find out.
Another question:Is the command "teleport"(used in events scripting) also disabled?

**Comment by heapoutofspace** [comment]
Teleporting to players should work, teleporting to coordinates probably fails.

**Comment by Seraphli** [comment]
So will teleporting to waypoint also fail?

**Comment by Seraphli** [comment]
I just find which block cause that error.Thank you!
