### ISSUE TITLE
Attribute "event" must be declared for element type "area"

### ISSUE THREAD

**Issue by Seraphli** [SimpleServer/SimpleServer#266]
I try to use area hooks in event scripting.
Here is my script.

```
<allblocks place="1+" destroy="1+" use="1+"/>

<!-- Dimensions -->
<dimension name="Earth">
    <area name="SpawnArea" start="189,0,241" end="187,127,239" event="creativeSwitch">
        <allblocks place="6" destroy="6" use="6"/>
    </area>
</dimension>

<!-- Events -->
<event name="onPlayerConnect"> 
    teleport #PLAYER 188,240,70
</event>
<event name="onPlayerRespawn"> 
    teleport #PLAYER 188,240,70
</event>
<event name="creativeSwitch">
    set '#action '#area to #POP Aexplode
    say #PLAYER #action
    if #action "enter" eq
      say #PLAYER "Entering spawn area"
      execcmd gamemode #PLAYER 0
    else
      say #PLAYER "Leaving spawn area"
      execcmd gamemode #PLAYER 1
    endif
</event>
```

console shows this:

> > Starting SimpleServer 8.4.3-d15c032
> > [SimpleServer] Error in config.xml: org.xml.sax.SAXParseException; lineNumber: 132; columnNumber: 85; Attribute "event" must be decl
> > ared for element type "area".
> > org.xml.sax.SAXParseException; lineNumber: 132; columnNumber: 85; Attribute "event" must be declared for element type "area".
> >         at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
> >         at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
> >         at simpleserver.config.xml.GlobalConfig.load(Unknown Source)
> >         at simpleserver.config.xml.GlobalConfig.load(Unknown Source)
> >         at simpleserver.Server.loadResources(Unknown Source)
> >         at simpleserver.Server.startup(Unknown Source)
> >         at simpleserver.Server.access$400(Unknown Source)
> >         at simpleserver.Server$Listener.run(Unknown Source)
> > [SimpleServer] Syntax error in config.xml! Config was not reloaded.
> > [SimpleServer] Syntax error in config.xml! Emergency shutdown...
> > Press any key to continue . . .

I don't know how to fix this.Please help....

**Comment by FedsRevenge** [comment]
I have the same issue when trying to create a switch for one player that will allow him to be at higher userlevel in nether and be free to do as much creative as possible, but restrict him to lower level and survival mode when entering earth... In the wiki the command "Aexplode" is listed under "Upcoming Feature" so that might be the problem.

**Comment by Seraphli** [comment]
Well,I didn't notice that.I thought the example wouldn't cause any error.They really shouldn't place that example there without a notification.Anyway, I really appreciate your reply!

**Comment by apirogov** [comment]
Sorry for the confusion... Currently you have to use onenter and onleave attributes...

The documentation is always on the state of the development version, but well maybe I'll seperate the "stable" and "dev" docs für event scripting after the next release...
