### ISSUE TITLE
new teleport functionality in MC 1.3

### ISSUE THREAD

**Issue by lucifer6642** [SimpleServer/SimpleServer#267]
The teleport command in Minecraft 1.3 allows you to teleport a player to a specific set of coordinates.

At the moment the only way I see to use this function is to use /rcon tp <player> <coordinates>

Will you either be able to fix the teleport command or define a new command that allows for this?

In the meantime, should people just define an alias in the config.xml file?
- SS compiled from git 2012-07-30 21:30 - Minecraft 1.3.1 pre

**Comment by lucifer6642** [comment]
tested with some edits to config.xml

```
    <command name="teleport" allow="4+" alias="tp2"/>
    <command name="tp" allow="4+" forwardonly="true" alias="tp"/>
```

Works but haven't tested for non-OP players.  Quite a few players on my server have teleport commands but not OP. I'd like to keep it this way.

**Comment by heapoutofspace** [comment]
I won't extend the `/tp` command to accept coordinates, there's already a `/warpto` command for that purpose. SimpleServer won't even use the new command internally since it's extremely unsafe and limited.

**Comment by lucifer6642** [comment]
No worries. Somehow I missed that command being noticed in the config. There's no mention of it in the command list on the Wiki.

> won't even use the new command internally since it's extremely unsafe

By that I'm assuming you mean because you can teleport inside solid objects or above pits. If the /warpto command uses a bot like the other warp commands, does it check to see if the destination has enough room for the player to exist there?

Closing this issue since there is a command to do it but I'd appreciate a reply on my question above please :)

**Comment by heapoutofspace** [comment]
The `/warpto` command won't check for space itself, but when spawning a bot inside a block its spawn position is automatically moved upwards to the surface.

**Comment by lucifer6642** [comment]
Excellent. Thank you very much sadi.This will be quite handy for myself and my server admin team.

Saves having to warp to the jail before teleporting someone to you. Just port them straight there :)
