### ISSUE TITLE
/spawn command on freshly created world

### ISSUE THREAD

**Issue by lucifer6642** [SimpleServer/SimpleServer#268]
I don't know if this was an issue in all versions of SimpleServer...

1) Fresh install of SimpleServer
2) Log in to server
3) Type /spawn
4) Teleported to X:0 Z:0 -- not actual spawn point --
5) Disconnect and shutdown server
6) Start up SS and log in again
7) /spawn works properly again -- send you to spawn point --

This is probably due to a file not being created at first run / world creation.

Other than advising people to start up the server, stop it and start again when creating a fresh world, is there any way to resolve this?

**Comment by heapoutofspace** [comment]
I can't reproduce that, when executing your steps I get teleported to 0/62/0, but there's no crash. Do you see any errors in the console?

**Comment by lucifer6642** [comment]
I didn't say a crash. But it does teleport you to 0:62:0, not to the actual spawn point.

The spawn point on the map was somewhere else, can't remember X,Z position but it was in the order of -100,64,200

On restarting the server, the /spawn command took you to the spawn point. Also tested dying without restarting server. It puts you at the correct spawn point. Only /spawn command didn't seem to work correctly without restarting.

PS - edited original issue to make things more clear,

**Comment by heapoutofspace** [comment]
Ah sorry, I assumed the "Disconnect and shutdown server" part was happening on its own. The default is indeed 0/62/0, I'll fix that when I find time.

**Comment by lucifer6642** [comment]
Good stuff. You deserve a medal for answering issues at 4am mate.

Although could you (or someone) update the documentation in the meantime to suggest that people do a restart in between world generation and actual use? It's not that big an issue as long as you know it's going to happen :)

**Comment by apirogov** [comment]
IMHO, thats a good idea anyway - I always let SS just generate the world and configs, save, and shut it down, before starting up and actually use it for anything ;)

And as far as I see, the Wiki installation guide already explicitly tells you:
1. Run launch.bat to start the server for the first time. ...
2. Now stop the server again by typing stop into the server console.

So consider this done :P
