### ISSUE TITLE
Backup issue

### ISSUE THREAD

**Issue by lucifer6642** [SimpleServer/SimpleServer#269]
Either the first time the autobackup time comes around or /backup is issued manually, the console window shows

```
2012-08-01 19:49:01 [INFO] Saving...
2012-08-01 19:49:01 [INFO] Saved the world
```

The backup does not continue though, even after waiting for ten minutes. When I stop the server, I get this

```
[SimpleServer] Stopping server...
[SimpleServer] Stopping Server...
[SimpleServer] Server is currently Backing Up/Saving...
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
        at java.util.concurrent.Semaphore.acquire(Unknown Source)
        at simpleserver.Server.shutdown(Unknown Source)
        at simpleserver.Server.access$700(Unknown Source)
        at simpleserver.Server$Listener.run(Unknown Source)
2012-08-01 19:49:54 [INFO] Stopping the server
2012-08-01 19:49:54 [INFO] Turned off world auto-saving
2012-08-01 19:49:54 [INFO] Stopping server
2012-08-01 19:49:54 [INFO] Saving players
2012-08-01 19:49:54 [INFO] Saving worlds
2012-08-01 19:49:54 [INFO] Saving chunks for level 'world'/xd@2ba46bc6
2012-08-01 19:49:54 [INFO] Saving chunks for level 'world'/xc@379faa8c
2012-08-01 19:49:54 [INFO] Saving chunks for level 'world'/xe@5375e9db
java.net.SocketException: socket closed
Closing listening thread
[SimpleServer] Backing up server...
[SimpleServer] Backup saved: backups\2012-08-01-19-50.zip
[SimpleServer] Server stopped successfully!
```

Currently running SimpleServer 8.4.4 with Minecraft 1.3.1 - Config files and map are ongoing from previous versions of SimpleServer and Minecraft.

**Comment by tazorax** [comment]
Same problem here :(

**Comment by lucifer6642** [comment]
Also tested with fresh install of SimpleServer and Minecraft. Same result so definitely not a problem with old config file.

---edit---

Shooting in the dark here as I'm not a coder. Is it something to do with the way Minecraft handles the different dimensions as 3 worlds now ?

--edit again---

Further testing. In case it was because any dimensions hadn't been fully formed, I created a new world and went to both the nether and The End before trying backup. Same result.

**Comment by VanillaDeath** [comment]
Same here. Backup feature broken on ubuntu-server 12.04 32-bit with OpenJDK7 JRE and latest everything.

**Comment by felixwiemuth** [comment]
If there was a recent change in Minecraft on where the map is stored, this will probably be the reason for the bug
(The last change to the SimpleServer backup system was on Nov 21, 2011).
It currently takes the folders "world" and "world_nether" from the server directory for the backup, so if Minecraft doesn´t store the map like this anymore, the backup isn´t done correctly.
How are things saved now?
I am planning to improve the backup feature anyway in the next time, introducing rollback etc.

**Comment by lucifer6642** [comment]
The actual directory structure for the world seems to be the same. 

On 1.2.5 when you shutdown the server (with simpleserver or without) it saves chunks then shuts down.

On the later weekly snapshots and then on 1.3.1, it shows it saving 3 times, like so.

```
2012-08-13 05:06:22 [INFO] Saving chunks for level 'world'/xd@1c51917
2012-08-13 05:06:22 [INFO] Saving chunks for level 'world'/xc@3bb16e20
2012-08-13 05:06:22 [INFO] Saving chunks for level 'world'/xe@7db5157d
```

Maybe it's just the way that MC now interacts with the saved dimensions

**Comment by lucifer6642** [comment]
Updated Minecraft to 1.3.2 and now the saving strings are a bit more sensible.

```
2012-08-19 18:50:16 [INFO] Saving chunks for level 'world'/Overworld
2012-08-19 18:50:16 [INFO] Saving chunks for level 'world'/Nether
2012-08-19 18:50:16 [INFO] Saving chunks for level 'world'/The End
```

Mentioned before that I'm not really a coder as such but when I look in AutoBackup.java there is a section that checks for the existence of Nether but I didn't see one for The End. Wonder if this is related?

**Comment by lucifer6642** [comment]
Blerg... It seems that the backup process works perfectly if you have bukkit installed.

I'd rather not have to use bukkit if at all possible. And yes, I know that some rehash of bukkit is probably being merged into Minecraft as the backend mod API. 

I hope someone can spare the time to look into this.

**Comment by felixwiemuth** [comment]
I need some more information:
- Execute /backup from server console or in-game?
- Does it work when you didnt go to Nether/End ever?
- Is the backup correct even though there is an error message?

I tested with a fresh install and the first /backup worked as normal. The second time it didnt continue as described before but when stopping the server, the backup is created.

What catches my eye is this part:

```
2012-08-01 19:49:01 [INFO] Saving...
2012-08-01 19:49:01 [INFO] Saved the world
```

Because it should rather be

```
2012-08-24 11:38:20 [INFO] Saving worlds
2012-08-24 11:38:20 [INFO] Saving chunks for level 'world'/Overworld
[SimpleServer] Backing up server...
2012-08-24 11:38:20 [INFO] Saving chunks for level 'world'/Nether
2012-08-24 11:38:20 [INFO] Saving chunks for level 'world'/The End
[SimpleServer] Backup saved: backups/2012-08-24-11-38.zip
```

like it currently is when stopping the server.

**Comment by felixwiemuth** [comment]
The problem was that the backup system hanged after initiating the minecraft server to save because it did not announce it finished saving. The fix fill be included in the next release.

**Still, could somebody tell me how/where all components of a minecraft map are saved?
I'd like to check if the backup system still takes the correct files.**

**Comment by apirogov** [comment]
Why not just backup the whole world/ directory? That should contain everything of the map :O

**Comment by felixwiemuth** [comment]
Because there was/is(?) a "world_nether" directory. So it could be anything, I just don't know.

**Comment by apirogov** [comment]
Oh :O Didn't know that.. and seems kind of weird that the map should be split over multiple directories oO

**Comment by lucifer6642** [comment]
Using a vanilla server, everything is stored in the world folder. If you use bukkit then there are 3 folders; world, world_nether, world_the_end.

Needs to take account of both types. Not sure if other alternate jars would use different structures.

**Comment by felixwiemuth** [comment]
Thanks! Do the bukkit folders also depend on the "level-name" option in server.properties (like with the vanilla server or SimpleServer)? Furthermore, I found out that with bukkit you can even chose where to save the world folders - we will only support the default setting then (inside the main directory).
I can upload a SimpleServer pre-release when I'm finished, it would be nice if you could test it, also with bukkit.

**Comment by lucifer6642** [comment]
I'll quite happily test it both with and without bukkit.

Bukkit does take note of the "level-name" but by default bukkit creates the 3 folders per map so that multiworld works. If you use the "level-container" option to choose where the folders are, it still has those three folders inside it. 

If SimpleServer was to wait for the save to complete and then just back up the whole folder regardless of it's contents, that would be fine. Although there would have to be an edit to the Wiki in the bukkit entry. Users will have to make sure they use the "world-container" option in bukkit's config and make sure that the folder name is the same as the "levelName" option in simpleserver.config

**Comment by lucifer6642** [comment]
Discovered something else as well while looking at this. It isn't an issue on my server so I didn't notice. At the moment if running a bukkit server, SimpleServer will not be backing up your "world_the_end" folder. Only the main folder and the nether.
Hope this doesn't impact people too much while awaiting new build :)

PS - Sorry for the 12 day gap earlier in my posts. Guild Wars 2 has been eating my time.

**Comment by felixwiemuth** [comment]
Don't worry about what directories are backed up. I rewrote that whole thing and I will also make a Wiki entry for this.

Did I get you right that SimpleServer should only consider the `level-container` for map backups if bukkit is used?
If bukkit doesn't use the minecraft server's `level-name` option when "level-container" is enabled, it indeed would make sense to name the container with the `level-name`.

**Comment by lucifer6642** [comment]
levelName - set in simpleserver.properties and then written to server.properties
level-container - set in bukkit.yml

Vanilla MC - complete world structure stored in

```
 .\<levelName>
```

Bukkit - a bit more weird 

```
.\<level-container>\<levelName>  for Earth
.\<level-container>\<levelName>_nether  for Nether
.\<level-container>\<levelName>_The_End  for The End
```

if level-container is undefined then

```
.\<levelName>  for Earth
.\<levelName>_nether  for Nether
.\<levelName>_The_End  for The End
```

**Comment by felixwiemuth** [comment]
Is there any disadvantage of using a level container with bukkit? Or is it simply the switch in the `bukkit.yml`?
If it`s really simple I think it would make sense to force bukkit users to use the level container.

**Comment by lucifer6642** [comment]
Nope. No issue with it at all. It's just not a default setting. I think anyone setting up a server that uses Bukkit AND SimpleServer could be considered sensible enough to read the instructions :)

**Comment by felixwiemuth** [comment]
So finally most of the work is done and the coming version can be tested.
Please refer to the new [issue](https://github.com/SimpleServer/SimpleServer/issues/273).
