### ISSUE TITLE
Possible problem relating to books

### ISSUE THREAD

**Issue by lucifer6642** [SimpleServer/SimpleServer#270]
This may be a generic MC issue, apologies if that's the case but didn't see anyone else with problem in bug list on minecraftwiki.

Tried to create a book several times today. Managed to do it successfully once but most often I get this happening.

```
[SimpleServer] java.io.IOException: Unable to parse unknown PlayerStream packet0x6d for player Lucifer_LLS (after 0xfffffffa
[SimpleServer] PlayerStream error handling traffic for #ip removed# (fffffffa)
java.net.SocketTimeoutException: Read timed out
[SimpleServer] java.io.EOFException
[SimpleServer] ServerStream error handling traffic for #ip removed# (23)
2012-08-02 01:48:37 [INFO] Lucifer_LLS lost connection: disconnect.genericReason
```

When it did work, the book only contained 16 characters, don't know if creating a longer one is causing a problem. It's still well within Minecraft limits though.  Pasting section symbols ( § ) for formatting shouldn't be a problem either should it?

**Comment by lucifer6642** [comment]
Tested again. Managed to get a 1 page book with formatting codes in to work. Also managed a 5 page book with one word per page.

It seems to be a problem depending on how much data is entered into the book window in one go, whether it is typed or pasted.

**Comment by FedsRevenge** [comment]
I get the same error when trying to write a book.

**Comment by felixwiemuth** [comment]
Because this is very likely related to Minecraft´s protocol(changes) I cannot help here, but I can try to get someone at it.
You could help by reporting in which release this bug occured first so we could track the corresponding protocol changes.
