### ISSUE TITLE
XP command not working

### ISSUE THREAD

**Issue by Traxis** [SimpleServer/SimpleServer#271]
If i use the command like this "/xp mynick 500" it gives me "2012-08-06 14:34:57 [INFO] 'mynick' is not a valid number" on the console. Using "/xp 500 mynick" doesn't work either, and using the command within the console gives the same result.

I tried the command with the vanilla server and it works perfectly.

**Comment by ghost** [comment]
I can reproduce this error. 

Using "/xp PLAYER_NICK XP_AMOUNT" gives the following error in server console

> 2012-09-21 22:32:41 [INFO] Can't find user, was one provided?
> Usage: /xp amount [player]

Using "/xp XP_AMOUNT PLAYER_NICK" gives the following error returned in game

> Player XP_AMOUNT is not online

I am using the latest build of SS and Bukkit
