### ISSUE TITLE
Could older versions be available for download?

### ISSUE THREAD

**Issue by lucifer6642** [SimpleServer/SimpleServer#272]
I was trying to see if SimpleServer could be run behind a Tekkit server.

Current Tekkit release is designed around Minecraft 1.2.5.   Unfortunately, I cannot find my older backup of SimpleServer.

Does anyone have an archive kicking around please?

**Comment by lucifer6642** [comment]
Excuse my ignorance of how git works. Didn't realise how easy it is to get older commits :-\

**Comment by fugenSnot** [comment]
I know the commits are easy to get to,but how exactly do you know which version the commits are made for? I was looking around on the commit list, but wasn't sure how this was done >:

EDIT: I figured it out. For anyone after me who is looking for the same thing, check on protocol builds and those will tell you the version that that simple server was made for.

EDIT2: I thought I figured it out. I'm not entirely sure what I'm supposed to do once I've found the commit I need. If someone could help point me in the right direction, I'd be super grateful.

**Comment by felixwiemuth** [comment]
Hi, there was just someone else asking for it: [issue](https://github.com/SimpleServer/SimpleServer/pull/288#issuecomment-11611960).
We have a [wiki page](http://github.com/SimpleServer/SimpleServer/wiki/Compiling-Your-Own-SimpleServer.jar-Version) about it and I extended it a little so you know better what to do.

**Comment by fugenSnot** [comment]
Thanks for that! I was trying to get it to work with FeedTheBeast (currently at 1.4.2) and needed the network help that SimpleServer provides :+1:

ADD: Alright, So the issue now isn't so much whether or not I can get the commit I need, but rather that I need a feature (Forge Support) from a later version of SS that isn't available in the version of SS that I need to use (8.4.5 for MC 1.4.2). So at this point I'm stumped XD Thank you anyway for your help on the issue!
