### ISSUE TITLE
SimpleServer crashes with 1.6.4

### ISSUE THREAD

**Issue by blaubaer** [SimpleServer/SimpleServer#28]
I got everytime the follwoing command when I connect to the server:

[SimpleServer] java.io.EOFException
[SimpleServer] PlayerStream error handling traffic for xxx.xxx.xxx.xxx
[SimpleServer] java.net.SocketException: Broken pipe
[SimpleServer] ServerStream error handling traffic for xxx.xxx.xxx.xxx
[SimpleServer] Socket Closed: xxx.xxx.xxx.xxx
java.net.SocketException: Connection reset

With SimpleServer 8.1.0 alpha-5412eb7.

**Comment by heapoutofspace** [comment]
I can't reproduce this. Did you run SimpleServer successfully before?

**Comment by blaubaer** [comment]
Yes. We run this with 8.0 of SimpleServer and 1.5.x minecraft. We god no problems with this version. I delete all jar and configuration files and also got this problems.

**Comment by heapoutofspace** [comment]
Did you craft a map already?

**Comment by blaubaer** [comment]
We updated the server with the same map. We do not create a new one.

**Comment by heapoutofspace** [comment]
I meant the new map item. Most of the changes only concern the mapping and nether support. Have you set any javaArguments in simpleserver.properties? If so remove them and try again.

**Comment by blaubaer** [comment]
Oh... I always spawn on the point where I last stand.. and I spawn on a Stone Pressue Plate which is connected to a Irondoor. Every time when I step on one of this plates the server produces this message. If I start minecraft server without SimpleServer I do not get this problem.

**Comment by heapoutofspace** [comment]
Thanks, this sounds way more reproducible :D

**Comment by blaubaer** [comment]
No we have no javaArguments and do not use nether support.

**Comment by PTY997** [comment]
I am having this problem too. people can connect but then they get kicked out with Internal exception: java.net.sockettimeoutexception: Read Timed out

**Comment by Lockhead** [comment]
Some update on this, we didn't think that it is connected to the pressure plate, we can reproduce this now really easy, every time sombody opens or closes a door, every other player in range is disconnected immediately.

leave me or blaubaer a pm if you want to know the server address so that we can show you this...
