### ISSUE TITLE
Simpleserver broken with 1.4.4?

### ISSUE THREAD

**Issue by ricrick** [SimpleServer/SimpleServer#283]
When using 8.4.5 with the latest 1.4.4 minecraft_server.jar, the command prompt displays "starting minecraft version 1.4.4" but when you log in as a 1.4.4 client, it does not allow you to connect to the server as the version displays 1.4.2 on the server list screen.

If bypassing simpleserver, it will allow using the same client. and minecraft_server.jar

**Comment by Lockhead** [comment]
Protocoll version was bumped from 47 for 1.4.2 to 49 for 1.4.4 and SimpleServer is no transparent proxy, so we have to wait for an update.

PS: for now it seems that the increased protocoll version is the only change

**Comment by ghost** [comment]
I am not sure if this will work for you, but if I do a direct connect to my server I am able to get on. Some commands are broken, like teleport, but over all it works from what i have seen.

Running latest dev build of bukkit.

**Comment by Lockhead** [comment]
If you login directly to your Server nothing that SimpleServer provide will work. And as SS starts the Server in Offline Mode you are open to fake Clients that can easly grief your whole world. So for me that is no solution. SimpleServer is the only daemon that can bind to a public routed ip. The minecraft server listens only on 127.0.0.1. If you really can connect to your server directly, why are u using simpleserver?

**Comment by felixwiemuth** [comment]
Ok seems we have to update SimpleServer regarding the protocol changes.
We will do a release as soon as possible.

**Comment by felixwiemuth** [comment]
Version 8.4.6 for Minecraft 1.4.4 is released.
