### ISSUE TITLE
Simpleserver 1.6.4 Map loading issue

### ISSUE THREAD

**Issue by PTY997** [SimpleServer/SimpleServer#29]
Hi i recently updated and got it all workign but when i connect i seem to be floating in blue air and only a few blocks are spawning, the map doesn't seem to want to load any help?

**Comment by vorpalhex** [comment]
I've had this issue, but it does not seem to be a SimpleServer issue.  Unfortunately I am not 100% certain as to the cause.  Can you confirm by running minecraft_server.jar directly instead of using SimpleServer, to see if the issue persists?

**Comment by PTY997** [comment]
Yes if i use the MC.jar file the the problem goes.

Update:

When I sit on the SSserver waiting for it to load I get the internal error read timed out

**Comment by dola** [comment]
according to this tweet (http://fwd4.me/02T4) from notch, those problems are not in SimpleServer but in the vanilla server. So there might be an update tomorrow on the vanilla to fix this.

**Comment by vorpalhex** [comment]
I'm closing this for now. If the update doesn't fix it in this case, we can re-open the issue.

**Comment by PTY997** [comment]
ok but this only happens when i use the SimpleServer since i updated it it worked fine for 1.5

**Comment by heapoutofspace** [comment]
See Notch's [tweet](https://twitter.com/#!/notch/status/74182283631923200)
