### ISSUE TITLE
Fireworks crash simpleserver

### ISSUE THREAD

**Issue by ricrick** [SimpleServer/SimpleServer#290]
It'll disconnect players in the fireworks visible area.

**Comment by ginbot86** [comment]
Could you give a bit more information as to the error itself? (eg. console logs, whether you're using vanilla or Bukkit etc. and any server mods that you are using, the platform your server is on)

**Comment by ricrick** [comment]
Using vanilla, no mods installed, doesn't log any error, but disconnects players in range and it allows player to log back in but immediately disconnects them, this lasts a short period of time.

**Comment by ginbot86** [comment]
Do you have any console output that you could provide?

There is a known issue with vanilla 1.4.6 and fireworks. If the firework rocket has no data to indicate what it will look like, it will immediately kill the connection with 'end of stream'.

**Comment by Triforce9** [comment]
Mojang actually resolved this issue in the 1.4.7 Pre-Release (http://mojang.com/2012/12/minecraft-1-4-7-pre-release/). It hasn't been pushed to the launcher yet, but it was supposed to be available right after the new year.

Either way, it's compatible with 1.4.6 clients, and according to the blog post I linked to, "...has almost no bytecode changes..." So it ( _theoretically_ ) should be compatible with SimpleServer 8.4.7.

**Comment by iBotPeaches** [comment]
This was a bug with the original vanilla MC release. I can no longer duplicate this.
