### ISSUE TITLE
No player names in join messages

### ISSUE THREAD

**Issue by bioxz** [SimpleServer/SimpleServer#297]
The join message just shows " joined the game" without a player. Also every teleporter bot is shown as a new player and keeps on the playerlist for a few seconds.

**Comment by ginbot86** [comment]
I haven't experienced the first issue that you mentioned, but the second has to do with the way that teleports are implemented in SimpleServer.

I myself haven't had much time as of late to work on SimpleServer so I can't provide much more information than this.

**Comment by bioxz** [comment]
I was able to replicate this bug with a fresh installation. The bots being shown on login could be a consequence of the missing player names.

**Comment by ginbot86** [comment]
Whart sort of platform are you running your server on (OS name/version, Java version, etc.)?

**Comment by bioxz** [comment]
My server:
Debian GNU/Linux 6.0 with java version "1.6.0_18" (OpenJDK)

My dev system:
Debian GNU/Linux 7.0 with java version "1.7.0_03" (also OpenJDK)

**Comment by ginbot86** [comment]
Ah, I see. My setups are all Windows-based so I can't do any testing on a Linux-based platform.

**Comment by Xyvius** [comment]
I am running on a Win 7 platform and get this as well. Just says " joined the game" whenever anyone joins or teleports.

**Comment by ginbot86** [comment]
Do you have any screenshots or console output? I so far haven't run into this when running my servers.

**Comment by iBotPeaches** [comment]
I can dupe this. I'll look into it
