### ISSUE TITLE
Protocol version bump to 61

### ISSUE THREAD

**Issue by bioxz** [SimpleServer/SimpleServer#298]
With Minecraft 1.5.2 the protocol version has been changed to 61. Updated clients are unable to join from the server page (join button is greyed out), direct connect works.

**Comment by iBotPeaches** [comment]
http://ibotpeaches.com/SimpleServer.jar

Let me know if that works. Just submitted pull request to fix.

**Comment by bioxz** [comment]
Working for me, already changed it in my own fork. Thanks
