### ISSUE TITLE
1.6.x support

### ISSUE THREAD

**Issue by iBotPeaches** [SimpleServer/SimpleServer#306]
- [x] Add support for `/spreadplayers`
- [x] Add support for `/playsound`
- [x] Adapt `/gamerule` for new attributes `naturalRegeneration` and `doDaylightCycle`
- [x] Update `give-alias-list` for new blocks
- [x] Update protocol spec to 73
- [x] Add support for JSON chat new format
- [x] Adapt Color enum to also deliver String format of color, (EX `Color.Green = "green"`), to pass to JSON msg.
- [x] Update Bot to newest protocol
- [x] Maintain spaces
- [x] Check license is in all new files
- [x] Look into new authentication type
- [x] Test for regression

Progress can be seen on my `master` branch here: https://github.com/iBotPeaches/SimpleServer

**Comment by iBotPeaches** [comment]
Finished the new protocol and new messaging changes. Need to test messaging a lot though, since it seems MOTD, Private, Global, PvP, Notices, etc all use different messaging types. Need to capture all inbound and divert properly.

Updated initial list w/ more items.

**Comment by heapoutofspace** [comment]
Fortunately servers use the exact same authentication method :+1:

**Comment by iBotPeaches** [comment]
Merged into mainline.
