### ISSUE TITLE
8.4.9 broken commands

### ISSUE THREAD

**Issue by JakeDiFebo** [SimpleServer/SimpleServer#308]
The commands for Warp and Home are broken, or so it seems. I have checked all of my config file and nowhere have I limited my player's ability to warp.

Please help, much appreciated.

**Comment by iBotPeaches** [comment]
What version of MC are you on?
Any errors when that happens, or it just "doesn't" work?

8.4.10 is out, but its only for v1.6.2 (which is why I asked): http://ibotpeaches.com/simpleserver/

**Comment by JakeDiFebo** [comment]
I am running 1.5.2 with 8.4.9 and your link confuses me; do I simply take the simpleserver.jar and replace the old one? Well, somehow I managed to miss 8.4.10 but yeah, whenever I type in "/home" or "/warp [location]", I simply receive a message from the server saying "Teleporting failed."

**Comment by iBotPeaches** [comment]
http://ibotpeaches.com/simpleserver/

What I linked to has them in folders based on Minecraft versions (ex 1.5.2 / 1.6.2, etc).
