### ISSUE TITLE
Use the wrapper of tanukisoftware.com

### ISSUE THREAD

**Issue by blaubaer** [SimpleServer/SimpleServer#31]
Hi!

What you think about http://wrapper.tanukisoftware.com?

This is a good way to create a real daemon. I integrate it manually but it would be very cool that this will be shipped with SimpleServer to make minecraft to a real damonizable server.

**Comment by heapoutofspace** [comment]
This is clearly not the right choice for a open source project. On unix system it's easy to set SimpleServer up as an upstart job or a simple init script. I might add a tutorial with an example script sometime.

**Comment by blaubaer** [comment]
It is possible to obtain a GPL version of this wrapper.

**Comment by heapoutofspace** [comment]
This may be true, but it's still not needed. You can even start the launch.sh with start-stop-daemon without problems. The only thing missing is a tutorial on how to do that.
