### ISSUE TITLE
Problems with update of lights

### ISSUE THREAD

**Issue by blaubaer** [SimpleServer/SimpleServer#33]
If you destroy blocks in a cave where you place torches sometimes the light updates came after a few seconds (not realtime) and sometime you have to disconnect and reconnect to get the light update.

Without SimpleServer it work perfectly.

**Comment by vorpalhex** [comment]
Noted as an issue on Minecraft itself. SimpleServer does add in some overhead, what are your top and free stats? How much processor and ram usage, both with and without SimpleServer?

**Comment by heapoutofspace** [comment]
Notch confirmed on [Twitter](https://twitter.com/notch/status/74182283631923200) that this is a minecraft bug.

**Comment by blaubaer** [comment]
Ok sorry for that.
