### ISSUE TITLE
Cant acess simpleserver.jar

### ISSUE THREAD

**Issue by legoracer171** [SimpleServer/SimpleServer#39]
When I try to start the server it says it cant access simpleserver.jar, what do I do?

**Comment by vorpalhex** [comment]
chmod u+rwx, make sure everything is owned by the same user. (Also make sure simpleserver.jar is actually there and correctly named of course)

**Comment by legoracer171** [comment]
I do not see simpleserver.jar in the folder, so would I need to download a different version or what?

**Comment by dola** [comment]
you might downloaded the source code instead of the builded release. 
Just use the link out of [the forum](https://github.com/downloads/SimpleServer/SimpleServer/SimpleServer.zip), download the zip, extract the whole content and then run it.

**Comment by legoracer171** [comment]
Thanks
