### ISSUE TITLE
alwaysDay option

### ISSUE THREAD

**Issue by heapoutofspace** [SimpleServer/SimpleServer#45]

**Comment by ghost** [comment]
There currently exists an advanced time command in the server - "time day freeze". You can use that for now.

**Comment by heapoutofspace** [comment]
I know, I [built](https://github.com/SimpleServer/SimpleServer/commit/668ea81a8545a82b7eb4f77b20c5a87d0f2f3cbe#diff-3) this.
The problem with it is, that the time unfreezes every time the server is restarted.

**Comment by ghost** [comment]
Sorry, didn't notice that you implemented it. Was just trying to give some advice until the new settings parameter is implemented.

**Comment by ghost** [comment]
And now I'm just feeling ashamed because you are the main author of project. Sorry.

**Comment by heapoutofspace** [comment]
No problem, I appreciate your helpfulness. : )

**Comment by ghost** [comment]
Also, I just came across an idea - maybe add a alwaysNight parameter? I think that it would be helpful for a hard survival map/server. If you add the night parameter, maybe you can somehow make them both into a single timeMode parameter which has modes/choices 'normal', 'dayFreeze' and 'nightFreeze' (or something similar). What do you think?

**Comment by heapoutofspace** [comment]
I was planning to do something like this, I'm not quite sure yet how exactly I'm ending up doing it. But thanks for the hint, if you got any other ideas just open a new issue ;)
