### ISSUE TITLE
Permission.xml Emptied on Stop [SimpleServer 8.1.3-456cf01]

### ISSUE THREAD

**Issue by ghost** [SimpleServer/SimpleServer#47]
Hey there.

I seem to have an issue when I stop the SimpleServer via command-line. When I go to restart the console says my permission.xml has a syntax error. Upon investigation the file is empty and I end up having to paste in my permission file, save it then I am able to restart. I'm not sure if this is a simple CHMOD issue or a bug but this happens every start-up.

Much thanks.

**Comment by heapoutofspace** [comment]
There are a few people reporting this, I have to investigate. It never happened to me though.

**Comment by heapoutofspace** [comment]
This problem only seems to occur when there is no space left in the working directory. To address the issue we added the configuration files to the backups and delete old backups when the free space reaches a critical low.
