### ISSUE TITLE
Let guests open doors

### ISSUE THREAD

**Issue by heapoutofspace** [SimpleServer/SimpleServer#5]
This should be optional

**Comment by apirogov** [comment]
If a player uses something, a "block placement" packet with a value of -1 is sent, for any block type.

There already is the global and area setting allowUse, which sets who is allowed to use stuff. But this means either a player can use EVERYTHING, including doors, buttons, levers, chests etc, or NOTHING.

I doubt that there's a way to set this per block (although I'd like to), but prove me wrong...

**Comment by heapoutofspace** [comment]
You're partly right, guests would be able to use buttons and levers. Chests however are opened by right-clicking and can therefore still not be used. Also the item value holds the item id currently in the player's hand, it only is -1 if one doesn't hold anything. To decide if someone is digging or using something you should check the destroy status.

**Comment by apirogov** [comment]
Right click also sends this packet! I tested this feature in areapermissions a lot...

EDIT: Of couse right click works, after all its block PLACEMENT; its always the right click... and left click counts as usage if you just click and don't hold (like pressing a button with left click without tearing it down)

You're right that it only works currently with empty hands (if the user can not place any block, but allowed to use stuff)..

What do you mean by destroy status? You mean the status of player digging? But it only allows 0,2 and 4 (all not related to block usage)
Sorry if I just don't get it :D

**Comment by heapoutofspace** [comment]
If you don't want the player to destroy blocks but to use things, you can check whether he destroyed a block completely. You only need to block this packet.

**Comment by apirogov** [comment]
Aaah dammit of course :D So to sum up, usage is when:

Block Placement packet with blockid = -1 -> right click
Player Digging without finishing packet  -> left click

Is this correct or is something missing? I'm gonna improve the allowUse setting then..

BTW: Would it make sense to make that BAD BLOCK message not globally visible, but a player message? it could get quite annoying, when people use different areas and people just don't know what they can to where and it does not have to be griefing...

**Comment by heapoutofspace** [comment]
Unfortunately it's impossible to know whether someone is placing a block or right clicking on it. Both times the item that is currently held is sent, so we can't know if someone is placing tnt or just entering a minecart or opening a door. 

That bad block message is really annoying and I was planning to do this since the day I started using SimpleServer :D

**Comment by apirogov** [comment]
And imo this issue should be closed, cause when areapermissions get merged into master, allowUse basically IS the requested option, and now it's my job to make it work better... (but even if it stays as it is it is usable, just a bit inconvenient)

**Comment by apirogov** [comment]
Ok then there's no choice... allowUse MUST work with -1, cause that's the only thing we surely know can not be block placement...

Then I'm gonna explain it in the wiki, that people should hold nothing in their hands to use stuff in placing-restricted areas with allowed usage... It's ugly but it works, and finally, it is only applying in areas or for guests...
