### ISSUE TITLE
/admin

### ISSUE THREAD

**Issue by ghost** [SimpleServer/SimpleServer#50]

**Comment by vorpalhex** [comment]
What functionality is this supposed to have? You can already promote people to be server admins...

**Comment by vorpalhex** [comment]
Use the !rcon command

**Comment by vorpalhex** [comment]
Add yourself to permissions.xml and restart the server.

**Comment by heapoutofspace** [comment]
Quote from the [FAQ](https://github.com/SimpleServer/SimpleServer/wiki/Faq):

To make yourself admin, add `<player name="younickname" group="5" />` within the `<members>` section of the permissions.xml. Note that 5 is the admin group if you have a DEFAULT config, if you converted from the old SimpleServer version, the admin/owner group is most likely 4 (you can see it in the `<groups>` section).

**Comment by heapoutofspace** [comment]
It sure does. Did the server run while you changed the file? If so you have to type `reload` into the console to reload it.

**Comment by heapoutofspace** [comment]
Obviously you changed the permissions.xml and it's no longer valid. Can you post your config on [pastie](http://pastie.org)?
