### ISSUE TITLE
Adding a new file in the root directory that list current online players

### ISSUE THREAD

**Issue by maxleiko** [SimpleServer/SimpleServer#51]
The aim of this file is to be parsed by a web application (for example) to know who's online and if the server is up or down.
The server will add or remove players from the file on player's (de)connections. An option in simpleserver.properties will have to be set to true. (something like "useOnlinePlayersToFile" )
I've already started some coding but I'm not familiar with SimpleServer dev architecture, so am going slowly.

I've also thought about a SQLite db but I would like some feedback first :)

**Comment by vorpalhex** [comment]
Why go through all of this trouble? Check /proc to see if it's running.  As far as seeing who is online, just keep an eye on the logs, as they get updated in realtime - just keep an eye on join/leave entries.

**Comment by maxleiko** [comment]
You're absolutely right. Gonna make a PHP script to check these. Thanks a lot for the advice.

**Comment by vorpalhex** [comment]
Try shell_exec('cat server.log | grep lost');
On Jun 9, 2011 9:48 AM, "maxleiko" <
reply@reply.github.com>
wrote:
