### ISSUE TITLE
server properties file

### ISSUE THREAD

**Issue by gerrie** [SimpleServer/SimpleServer#54]
heej, 

Im getting this issue when i change "online-mode=false" in the "server.properties" file 

that it automatically changes the "false" in "true" and i dont want that i want it to be false cause i just play locally with my friend ( not the same network). is there a fix for that ??

**Comment by dola** [comment]
You can only change the properties of the server in the `simpleserver.properties` and while the server is not running. So set onlineMode in simpleserver.properties to true and start your server. Then simpleserver generates the correct server.properties automatically.
