### ISSUE TITLE
Subarea takes parent area name

### ISSUE THREAD

**Issue by yagotmilk** [SimpleServer/SimpleServer#55]
I've built a hotel that I'm going to run in minecraft and I've set the the name for the entire surface area of the hotel as "Hotel". However I've created subareas for the rooms and renamed each room to its own suite number. I've set each subarea so others can't go into rooms unless they are let in and then they can't grief anyone elses rooms. However if I use the /area command in for example a corridor, it says "Hotel" which is good. I then go inside a room and /area again and it still says "Hotel" rather than the subarea's name. Can anyone help me with this?

**Comment by dola** [comment]
This truly should not be like this.
Can you somehow give us access to your permissions.xml? The best would be if you paste it to [pastebin](http://pastebin.com/) and share the link here. So I can directly test it with your areas. (I recommend to replace private data like account names with some placeholders like Player1, Player2, etc.)

**Comment by yagotmilk** [comment]
http://pastebin.com/z9nWJKnN

Thanks for getting back to me so quickly! I'm probably doing something wrong but theres the link you requested.

Thanks in advance!

**Comment by heapoutofspace** [comment]
As far as I know y-coordinates are currently not supported. Just remove them from every point and everything should work.

**Comment by yagotmilk** [comment]
Oh, my area's wont be able to function I don't think if that is the case. All the suites in the hotel are stacked ontop of each other in the same x and z dimension but they are on separate floors, therefore being separated by their y dimensions. Is there a way round this and if not, can you tell me if you guys are going to support the y co-ordinate in a following update?

Thank You.

**Comment by heapoutofspace** [comment]
Adding the altitude shouldn't be hard, I have no idea why the author didn't implemented it. We'll add it for the next release.

**Comment by yagotmilk** [comment]
Thanks man! Much appreciated.

**Comment by dola** [comment]
done in 8.2
