### ISSUE TITLE
god mode?

### ISSUE THREAD

**Issue by NotDeadYet** [SimpleServer/SimpleServer#57]
I typed in the command /ddqd and it tells me god mode is enabled. I fall off a cliff and get hurt; then I thought that maybe I was only immune to creatures, but those still hurt.

**Comment by vorpalhex** [comment]
ddqd applies to breaking blocks.

**Comment by Triforce9** [comment]
/idbehold is for block breaking.
/iddqd is indeed for god mode.

If I remember correctly, god mode only stops players from hurting you.
