### ISSUE TITLE
clear inventory request

### ISSUE THREAD

**Issue by NotDeadYet** [SimpleServer/SimpleServer#58]
There should be a way to clear your inventory. I saw this in another server, and it came in handy when you were digging and you have all this useless dirt and rock.

example: 

/clear i -all       ;anyone can clear all their inventory
/clear <playername> -all            ;mod can clear a players inventory

**Comment by vorpalhex** [comment]
This doesn't fit in well with how SimpleServer works. SimpleServer acts as a proxy, and alters the data in transit. This would require altering the actual contents of a file on the server.

**Comment by heapoutofspace** [comment]
The player's dat files even seem to be cached, so this wouldn't work at all. If you want things like this, use Bukkit.
