### ISSUE TITLE
Improve allowUse / make Left click work

### ISSUE THREAD

**Issue by apirogov** [SimpleServer/SimpleServer#6]

**Comment by apirogov** [comment]
not possible ._.

**Comment by heapoutofspace** [comment]
Could you at least implement it for left clicking? The only thing right clicking would be needed is entering minecarts. Also it should ALWAYS be possible to leave a minecart (if it only work with empty hands it's ok).

**Comment by apirogov** [comment]
I think it already worked with left clicking before, but anyway, I looked at it and tweaked it a bit... Seems to work fine both right and left click.

If player is allowed to use AND destroy: Works as expected
When player cant destroy or use: Both actions fail with respective message
If player is allowed to use, but not destroy: Doors/buttons etc work, destroy fails with message
If player is allowed to destroy but NOT to use: Destroy doesn't work too -> "use" restriction overrides "destroy" (it makes kinda sense because of the packet rejecting of "start digging") -> shows message "can not use"

I for one always use right clicking for activating stuff because that way I'm sure I don't destroy it by accident...

Anyway... it should be fine now. You can test it too and close the issue if you think its ok ..
