### ISSUE TITLE
Time freezing through server

### ISSUE THREAD

**Issue by ghost** [SimpleServer/SimpleServer#60]
I would like to have the current time command `time number|day|night|unfreeze [freeze]` accessible from the server command-prompt, not only the client, or some other command added for freezing time from command-prompt.

**Comment by vorpalhex** [comment]
May I inquire as to why? It seems like you should be able to set it once in chat and then forget it.

**Comment by ghost** [comment]
I would like it because I might not want to log in just to freeze it. I just think that this would be a helpful command. If you don't think so, then okay.

**Comment by vorpalhex** [comment]
You should only need to log in once to freeze time unless you're restarting the server, at which point it may be moreso worthwhile to add it as a config file parameter.

**Comment by ghost** [comment]
About the value being frozen at launch, I know about #45. I didn't want it frozen all the time. I wanted it to be possible to freeze and unfreeze it at any point with a command. If you don't think that it's worth it, then it's just fine.

**Comment by vorpalhex** [comment]
Not my project primarily, so I'll leave that decision to Apirogov.
