### ISSUE TITLE
Command Permissions with Sub-Argument.

### ISSUE THREAD

**Issue by yagotmilk** [SimpleServer/SimpleServer#61]
Hey again,

I'm trying to set up iConomy with SimpleServer and I have it running with the CraftBukkit implemented as the alternate jar file and everything works. But now I'm trying to edit the access to the iConomy plugin commands using the permissions.xml. I'm sure I read somewhere in the wiki that you can edit permissions for Bukkit executables using the xml. The only issue I'm having is for formatting the "name" of the command as the majority of the iConomy commands have a sub argument after the "/money" command i.e "/money pay"

However if I set for example <command name="money pay" allow="1+"/> I get an error on server launch about nametokens? or NMtokens. So I'm just a little unsure of how I should format commands with a sub argument in the command permissions.

Can anyone help me?

Thanks Again.

**Comment by yagotmilk** [comment]
I think the example disappeared because of the syntax but it was " command name="money pay" allow="1+" " enclosed in the < > brackets.

**Comment by heapoutofspace** [comment]
I don't think this works right now. The only thing you can do is using the Permissions plugin for Bukkit. I'm planing to add a function to sync the group memberships and names between the two config files.

**Comment by yagotmilk** [comment]
Ah sweet, thank you for your support.
