### ISSUE TITLE
Bad Packet id <#number>

### ISSUE THREAD

**Issue by taranais** [SimpleServer/SimpleServer#65]
i recived this error on client side, with planes mod and IC.
Using simpleserver, version 8.1.3-d963d80, compiled version downloaded from here :
http://www.minecraftforum.net/topic/309373-software-simpleserver-wrapper-813-166/page__view__findpost__p__5338976

i think this should be related with this implementation (only commit related with modloademp found):

file:  /src/simpleserver/stream/StreamTunnel.java 

```
case (byte) 0xe6: // ModLoaderMP by SDK
    write(in.readInt()); // mod
    write(in.readInt()); // packet id   
    copyNBytes(write(in.readInt()) * 4); // ints
    copyNBytes(write(in.readInt()) * 4); // floats
    int sizeString = write(in.readInt()); // strings
    for (int i = 0; i < sizeString; i++) {
      copyNBytes(write(in.readInt()));
    }
    break;
```

i dont know if this will fix but here you are:

```
case (byte) 0xe6: // ModLoaderMP by SDK
    write(in.readInt()); // mod
    write(packetId); // packet id      <--- this line is the only change
    copyNBytes(write(in.readInt()) * 4); // ints
    copyNBytes(write(in.readInt()) * 4); // floats
    int sizeString = write(in.readInt()); // strings
    for (int i = 0; i < sizeString; i++) {
      copyNBytes(write(in.readInt()));
    }
    break;
```

i have just read the code form here, i haven`t compile it

sorry about my English.

PS:  minecraft-server.jar used works alone

**Comment by heapoutofspace** [comment]
It was indeed wrong, but your fix wouldn't work either. Join us on IRC (irc.euirc.net#SimpleServer) if you can't build it yourself.
