### ISSUE TITLE
Trapdoor/Hatch Redstone control

### ISSUE THREAD

**Issue by ghost** [SimpleServer/SimpleServer#66]
When trying to operate hatch with redstone circuit, SimpleServer throws an exception and disconnects player:
[SimpleServer] java.io.IOException: Unable to parse unknown ServerStream packet 0x3d for player X

**Comment by heapoutofspace** [comment]
Are you using the newest version (8.1.3)? This was a known bug in 8.1.1 and 8.1.2

**Comment by ghost** [comment]
Sorry, thought i did. I downloaded the new wrapper yesterday and i thought that it doesn't need updates. sorry for the mishap.
