### ISSUE TITLE
Wont Start

### ISSUE THREAD

**Issue by alpha828** [SimpleServer/SimpleServer#67]
Whenever I modify the SimpleServer.jar and change the alternate .jar in the simple-server.properties it wont start the server and in terminal it says corrupt simpleserver.jar. Why is this happening?

**Comment by vorpalhex** [comment]
You've done something to corrupt SimpleServer.jar . It is likely whatever modifications you are making are being made incorrectly.

**Comment by ghost** [comment]
You do not need to make any modifications to the SimpleServer.jar itself.
