### ISSUE TITLE
Do we really need SMP API support?

### ISSUE THREAD

**Issue by apirogov** [SimpleServer/SimpleServer#7]
The thread of SMP API was last updated last year, the official SimpleServer wiki lists only 3 mods basing on it and they have not been updated for a long time too and even the download links are broken...

I think no one uses this feature, so I suggest to remove it. The less unneccessary source code, the easier the project is to maintain... Moving on also means throwing away old stuff. What do you think about this?

EDIT: Now if I got it right, useSMPAPI should be set for usage with ANY mod. So maybe it should be at least renamed to something more generic?

**Comment by heapoutofspace** [comment]
I thought about renaming it too, but we'd have to add even more legacy code...

**Comment by apirogov** [comment]
Do you think it is really neccessary to make another converter script for a simple rename of a dumb boolean switch? You may call me not "user friendly" but I would just announce it...  I do not assume that the new version will work out of the box for everyone anyway, even with the included converter - 8.0 is gonna bring so much change that this would not make much of a difference anymore, imho...

**Comment by heapoutofspace** [comment]
Implementing this wouldn't take more than two lines of code which we could remove in the next version. I think it would save some users a lot of trouble and us some time answering their questions in the forum.

**Comment by apirogov** [comment]
Then lets just do it! I'll commit it...
