### ISSUE TITLE
permissions.xml gets emptied on changing onlinemode

### ISSUE THREAD

**Issue by jankazemier** [SimpleServer/SimpleServer#75]
Everytime I toggle onlinemode in simpleserver.properties I get the following exception:

[WARNING][permissions.xml] L. 1: Premature end of file.
[SimpleServer] org.apache.commons.configuration.ConfigurationException: Unable to load the configuration
[SimpleServer] Failed to load permissions.xml
[SimpleServer] Syntax error in permissions.xml! Emergency shutdown...

Which is caused by an empty permissions.xml. i have no clue as to why it is emptied. Removing the permissions.xml creates a new one on next startup (which does make minecraft work, however all permissions are lost).

edit: this happened while using server 1.7, although I suspect it will happen on all server versions?

**Comment by ghost** [comment]
I could not recreate this issue on Minecraft 1.7_01. The _permissions.xml_ stays OK when server is stopped and when the online-mode is changed. You do stop the server with the stop command, right? Also, what OS do you have?

**Comment by jankazemier** [comment]
Whoops, I guess you're right. I think it was because the server crashed because of a piston-bug. I'm using Ubuntu Server 11.04 (64 bit).

That's a bug too, but with a different cause. A server crash should not empty the simpleserver.properties.

You may close this issue if you think I should file a new bug.

**Comment by ghost** [comment]
The piston bug itself was a bug caused by Mojang and I think that they fixed that in 1.7_01. I am not really sure why the _permissions.xml_ got emptied on crash...
Do you have the logs from the crash? If you do, what do they say at the error?
