### ISSUE TITLE
/give Bug

### ISSUE THREAD

**Issue by mrxdst** [SimpleServer/SimpleServer#81]
I'm using simpelserver 8.2.1 with bukkit 953 and when I set forward all commands to true I get a bug.
When i type for example /give stone 10 i get a message in the chat "Can't find user stone"  (But i still get 10 stone).
However when i type /give stone without the quantity it works perfectly.
It's a bit annoying to get that message every time I use /give.

**Comment by ghost** [comment]
The problem is that `forwardAllCommands` means that nothing is read by SimpleServer. The aliases (names) like "stone", "tnt" and others are given by SimpleServer and Bukkit only knows the `/give playerName itemID amount` command.
Why did you set the `forwardAllCommands` to true in first place? I would suggest setting it to false.

**Comment by mrxdst** [comment]
But if Bukkit only knows '/give playerName itemID amount' how come i get my item when i type '/give itemName amount'

**Comment by ghost** [comment]
Not sure actually. I will look at this issue.

**Comment by mrxdst** [comment]
Thanks. The problem isn't that big because the /give command still works.
If it just was some way for simpelserver to filter the message out.

**Comment by ghost** [comment]
I am actually not having this issue. Are you having any plugin that also uses the /give command?

**Comment by mrxdst** [comment]
That's strange. I don't have any other /give plugin but the reason i "turned forward all commands" to false was because i wanted to use another permissions plugin and when simpelserver handled the commands the permissions plugin didn't work properly. Can it have something to do with the plugin because the message started to appear right after i got it all set up.
But the permissions plugin have nothing to do with /give?

**Comment by ghost** [comment]
I am not really sure what is happening here... Maybe some interference is somehow happening...

**Comment by mrxdst** [comment]
It must be something like that, I will try to play around with some settings and see if I can find a solution.

**Comment by mrxdst** [comment]
The message have now stopped appearing but i don't know why because my server config is the same as before.

**Comment by heapoutofspace** [comment]
If you set `forwardAllCommands` to true, _alL_ commands are forwarded, even after SimpleServer parsed them. You only need to set this flag if you want to monitor command usage with a Bukkit plugin. Setting the option to false should solve your problem.
