### ISSUE TITLE
flying

### ISSUE THREAD

**Issue by heapoutofspace** [SimpleServer/SimpleServer#83]
(If i manage to do it)

**Comment by ghost** [comment]
you mean to make support for planes mod (that would be reeealy great) or allow players to fly (float)?

**Comment by heapoutofspace** [comment]
Planes are already supported, I intend to let players fly somehow.

**Comment by ghost** [comment]
Again, i feel stupid, i didn't re-test it when i updated to latest version.

As for the flying thingy, i think it's just client-side mod and allow-flight set to true. But i suspect you want to make server-based solution... then you need to keep the client convinced that the player isn't moving down...  refreshing his vertical position... well, if effects of "gravity" are calculated on client side, as i shink they are, then the best you can hope for is sort of laggy hopping with no control of the flight. You can convince server, that players are walking on clouds, but not the client - unless modified.

**Comment by heapoutofspace** [comment]
There are some Bukkit plugins doing exactly that, so i figured it should be possible. One way to make it look smooth in the client is to emulate giant jumps. If possible i would prefer a more controllable flight like client mods offer it. I will see if and how well I can implement this after doing some testing.

**Comment by dola** [comment]
Obsolete now with the possibility to change gamemode (>1.8) with a command...

**Comment by acertain** [comment]
it would be kinda cool if you could fly in survival, and would be WAY easyer!!

**Comment by heapoutofspace** [comment]
Server side flying is very hard to control so I really recommend using creative mode.

**Comment by acertain** [comment]
I meant use the flying from creative in srvival w/ a command!
