### ISSUE TITLE
Refactoring Message System

### ISSUE THREAD

**Issue by dola** [SimpleServer/SimpleServer#86]
To support chatfoms like:
- GlobalChat
- DimensionChat
- GroupChat
- PrivateChat
- LocalChat
- AreaChat

with one /toggle MODE function to change standard and commands to use each mode for just one message.

**Comment by heapoutofspace** [comment]
Just a thougth: If you don't send global chat to the server we don't get the wrapping problem with bukkit.

**Comment by RadioRoscoe** [comment]
I like this idea. Especially the /toggle! It would also be nice to not have to type a player's full name in (just like the console).

**Comment by dola** [comment]
it works now and is a bit cleaner than before.
The only problem that maybe upsets some users is that the chat is not forwarded to vanilla / bukkit. So ChatLogPlugins won't work anymore.
I can think about providing an option for it that would require to recognize and ignore them when they come back from the server. (kind of wasting performance)

@RadioRoscoe: the /toggle command will be called /chat since it changes the chatMode entirely rather than toggle between two modes.

**Comment by NasiasDarkstar** [comment]
What about the way MMO's handle that sort of thing?

/p message - Group(party) chat
/d message - Dimension chat
/w message - Private(whisper) chat
/s message - Local chat
etc..

**Comment by dola** [comment]
This possibilities exist already. Currently they can be used with the following commands: (first is alias, second is basic command)

/g /group [groupId] - group chat to your own group or the specified one
/a /areasay - to the current area
/t /tell Player - as before private chat (and /r /reply to reply to the last private message)
/d /dimenion [Dimension] - Chat to specified or current dimension
/l /local - local chat (as before)
/global - globalChat (to be used if chatMode isn't global)

and therefore the possible chatModes for /chat are:
global (default), local, dimension [Dimension], area, group [groupId], private Player

I think like this they're quite intuitive and those that already existed aren't changed. If you got some other suggestions feel free to state them here.

**Comment by NasiasDarkstar** [comment]
Well, the previous suggestion was just an example; but the short-hand versions such as /g, /a, /t etc. are very good.
