### ISSUE TITLE
Player.java bug with localAddress / addressFactory

### ISSUE THREAD

**Issue by Axiom-o7** [SimpleServer/SimpleServer#87]
The "addressFactory" / localAddress code in Player.java (currently on lines 114 - 117) fails on certain servers. 
This has been happening ever since the "addressFactory" code was introduced to Player.java in December. 
I've compiled my own versions of simpleserver on every release since that update to work around the issue.

It's very easy to patch in Player.java, but a serious pain to do for every single update.
I would love to see a setting available in the simpleserver config to bypass this issue. 

A setting such as "portmethod_old=true" to select the old method would fix this:      

(replace lines 114-117 with the following, for anybody that sets the config bit)

intsocket = new Socket(InetAddress.getByName(null),
                             server.options.getInt("internalPort"));

Then keep the new method for anyone who doesn't set the bit.

Have not discovered why this happens, but it is a bad bug. It appears to create an infinite loop, possibly due to multiple IP addresses and domains on a single VPS, or virtual port assignments, while it needlessly cycles. 

Whatever the case, the above is the easiest fix. I imagine others have run into the same problem and gave up.

To clarify, 
The existing code fails / starts a loop on some servers:
      InetAddress localAddress = InetAddress.getByName(addressFactory.getNextAddress());
      intsocket = new Socket(InetAddress.getByName(null),
                             server.options.getInt("internalPort"),
                             localAddress, 0);

The Following Works on the affected servers (removing the localAddress lines):
      intsocket = new Socket(InetAddress.getByName(null),
                             server.options.getInt("internalPort"));

**Comment by heapoutofspace** [comment]
Have you ever tried to run it without your patch? As you can see in the code I added the exact code you posted some months ago.

**Comment by Axiom-o7** [comment]
Yes, thanks, I noticed the changes, but it still hangs and fails in the same spot, without bypassing the problem code.

I attempt the "released version" each time, when that fails, I download the source and comment out / remove the problem lines and recompile. 

 Unless I've missed an added switch or config setting to bypass this, it still hits the addressFactory line and freezes every time.

**Comment by heapoutofspace** [comment]
Can you please test if this fixes your issue? It's not exactly your solution but could work too.

**Comment by Axiom-o7** [comment]
Bingo!, that appears to fix it. Fantastic! 

Thanks so much for the fix!
