### ISSUE TITLE
/groupremove {player} - Removing players from members element with a command

### ISSUE THREAD

**Issue by NasiasDarkstar** [SimpleServer/SimpleServer#98]
Typing /groupremove {playername} would unset a &lt;player&gt; element within the &lt;members&gt; element.

This would set the players group back to the specified defaultGroup={int} option that's specified within simpleserver.properties

**Comment by dola** [comment]
We could think about adding a special 'default' parameter to the setgroup commands that could be issued instead of the groupId. But adding a whole new command for this would be a bit of an overkill...

**Comment by NasiasDarkstar** [comment]
The reason for the command would be to remove an entry from the XML file, instead of it just being altered to something else. So removing it from the XML file would make more sense instead of changing it to default.

For at the moment, it's currently:
PlayerGroup = Is player specified in permissions.xml-><members> ? get their group name :else: their group is default group.

It would make sense with cleanup, for example temporarily making somebody a temp moderator; the members attribute could get quite big if you run a large server and have to enter /setgroup player 2, then an hour or so later when the temp priv elevation is not needed any longer, typing /setgroup player default.

Unless of course, you mean typing /setgroup player default would remove the XML attribute entry relating to the players name anyway?

**Comment by dola** [comment]
I don't see why it what the advantage of deleting a player entry is over an adjustment of the player group if you only care about the group. (and anyway the entry would be exactly the same after it was newly created and if only changed)

However I think it would be more useful to have a command that removes all player related data (including chestLocks, private areas, custAuth information, home position and so on) to be able to cleanup the server.

If you really only want to set a player temorarily into a higher group I still recommend using the /setgroup command twice. I don't think this should happen very often... And you anyway would have to use two commands with your solution too.

**Comment by NasiasDarkstar** [comment]
Purely because it seems illogical to keep old un-required entries within the members attribute, when they aren't used anymore. It's all a bit pointless to have member record entries in the XML file when their group is equal to the default group. 

Just thinking on large scale here; When you could potentially have several hundred unused member records that are set to the default group, because the only way to remove them would be to remove them manually from the XML file.

Perhapps a compromise, then? /setgroup anyplayer default would remove the entry from the XML file (if it exists) where-as /setgroup anyplayer {int} would add an entry to the XML file (if player doesn't exist) else update the current entry with the new groupID. It'd make more sense than adding the new command this way too anyway, I suppose.
