### ISSUE TITLE
Log /tell

### ISSUE THREAD

**Issue by Triforce9** [SimpleServer/SimpleServer#99]
It would be nice if SimpleServer logged usage of the /tell command to the server.log, similar to the way vanilla minecraft server does.

**Comment by dola** [comment]
While developping the new [MessageSystem](https://github.com/SimpleServer/SimpleServer/issues/86) I already built a feature that allows to forward every single chatMessage (even those through privateChat, localChat, dimensionChat etc.) to the server. Like this they are logged automatically like global messages.
You can see a first version of it [here](https://github.com/SimpleServer/SimpleServer/commit/1ef298af4c909cd76c259863b9e41dbe6bc75525).

**Comment by Triforce9** [comment]
Ah, so that is what the new message system does; I understand it now.

**Comment by dola** [comment]
closing this. please refer to the [MessageSystem issue](https://github.com/SimpleServer/SimpleServer/issues/86).
